# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import encode_path_param
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..core.serialization import convert_and_respect_annotation_metadata
from ..errors.unprocessable_entity_error import UnprocessableEntityError
from ..types.annotation_item_payload import AnnotationItemPayload
from ..types.annotation_task_create_response import AnnotationTaskCreateResponse
from ..types.annotation_task_response import AnnotationTaskResponse
from ..types.bulk_create_items_response import BulkCreateItemsResponse
from ..types.bulk_update_items_response import BulkUpdateItemsResponse
from ..types.evaluator_link_response import EvaluatorLinkResponse
from ..types.evaluator_run_launch_response import EvaluatorRunLaunchResponse
from ..types.evaluator_run_request_entry import EvaluatorRunRequestEntry
from ..types.evaluator_run_response import EvaluatorRunResponse
from ..types.http_validation_error import HttpValidationError
from ..types.item_update_payload import ItemUpdatePayload
from ..types.paginated_response_annotation_task_response import PaginatedResponseAnnotationTaskResponse
from ..types.task_agreement_response import TaskAgreementResponse
from ..types.task_summary_response import TaskSummaryResponse
from .types.annotation_task_create_type import AnnotationTaskCreateType
from .types.get_agreement_annotation_tasks_request_bucket import GetAgreementAnnotationTasksRequestBucket
from .types.get_summary_annotation_tasks_request_order import GetSummaryAnnotationTasksRequestOrder
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawAnnotationTasksClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list(
        self,
        *,
        q: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[PaginatedResponseAnnotationTaskResponse]:
        """
        List annotation tasks with linked evaluators

        Parameters
        ----------
        q : typing.Optional[str]
            Case-insensitive substring search on `name`. Blank is a no-op

        limit : typing.Optional[int]
            Maximum number of items to return. Omit for no limit (all items)

        offset : typing.Optional[int]
            Number of items to skip before returning results

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[PaginatedResponseAnnotationTaskResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            "annotation-tasks",
            method="GET",
            params={
                "q": q,
                "limit": limit,
                "offset": offset,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PaginatedResponseAnnotationTaskResponse,
                    parse_obj_as(
                        type_=PaginatedResponseAnnotationTaskResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def create(
        self,
        *,
        name: str,
        type: AnnotationTaskCreateType,
        description: typing.Optional[str] = OMIT,
        evaluator_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[AnnotationTaskCreateResponse]:
        """
        Create an annotation task for annotators to label items against evaluators

        Parameters
        ----------
        name : str
            Task name, unique within your workspace

        type : AnnotationTaskCreateType
            Task type. Determines the shape of each item's payload.
            - `stt`: judge a transcript on its own
            - `llm`: judge one response with its conversation history
            - `llm-general`: judge a standalone `input -> output` pair
            - `conversation`: judge a full conversation

        description : typing.Optional[str]
            A description for the task. Omit for none

        evaluator_ids : typing.Optional[typing.Sequence[str]]
            IDs of evaluators to link when the task is created, in order. Each must be one you created or a built-in default. Omit to create with no linked evaluators

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[AnnotationTaskCreateResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            "annotation-tasks",
            method="POST",
            json={
                "name": name,
                "type": type,
                "description": description,
                "evaluator_ids": evaluator_ids,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    AnnotationTaskCreateResponse,
                    parse_obj_as(
                        type_=AnnotationTaskCreateResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get(
        self, task_uuid: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[AnnotationTaskResponse]:
        """
        Get one annotation task with linked evaluators, items, and labelling jobs

        Parameters
        ----------
        task_uuid : str
            Task to retrieve

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[AnnotationTaskResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"annotation-tasks/{encode_path_param(task_uuid)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    AnnotationTaskResponse,
                    parse_obj_as(
                        type_=AnnotationTaskResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def link_evaluator(
        self, task_uuid: str, *, evaluator_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[EvaluatorLinkResponse]:
        """
        Link an evaluator to a task, appending it to the display order

        Parameters
        ----------
        task_uuid : str
            Annotation task to act on

        evaluator_id : str
            The evaluator to link. Must be one you created or a built-in default

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[EvaluatorLinkResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"annotation-tasks/{encode_path_param(task_uuid)}/evaluators",
            method="POST",
            json={
                "evaluator_id": evaluator_id,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    EvaluatorLinkResponse,
                    parse_obj_as(
                        type_=EvaluatorLinkResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def add_items(
        self,
        task_uuid: str,
        *,
        items: typing.Sequence[AnnotationItemPayload],
        annotator_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[BulkCreateItemsResponse]:
        """
        Bulk-create annotation items in a task, optionally seeding human annotations

        Parameters
        ----------
        task_uuid : str
            Annotation task to act on

        items : typing.Sequence[AnnotationItemPayload]
            Items to insert. Insertion order is preserved

        annotator_id : typing.Optional[str]
            Annotator these initial annotations belong to. Required when any item carries annotations

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[BulkCreateItemsResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"annotation-tasks/{encode_path_param(task_uuid)}/items",
            method="POST",
            json={
                "items": convert_and_respect_annotation_metadata(
                    object_=items, annotation=typing.Sequence[AnnotationItemPayload], direction="write"
                ),
                "annotator_id": annotator_id,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    BulkCreateItemsResponse,
                    parse_obj_as(
                        type_=BulkCreateItemsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def update_items(
        self,
        task_uuid: str,
        *,
        updates: typing.Sequence[ItemUpdatePayload],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[BulkUpdateItemsResponse]:
        """
        Bulk-update item payloads in a task

        Parameters
        ----------
        task_uuid : str
            Annotation task to act on

        updates : typing.Sequence[ItemUpdatePayload]
            The new payload for each item you're updating. Entries not in this task, or referencing deleted items, are skipped

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[BulkUpdateItemsResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"annotation-tasks/{encode_path_param(task_uuid)}/items",
            method="PUT",
            json={
                "updates": convert_and_respect_annotation_metadata(
                    object_=updates, annotation=typing.Sequence[ItemUpdatePayload], direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    BulkUpdateItemsResponse,
                    parse_obj_as(
                        type_=BulkUpdateItemsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def create_evaluator_run(
        self,
        task_uuid: str,
        *,
        evaluators: typing.Sequence[EvaluatorRunRequestEntry],
        item_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        select_all: typing.Optional[bool] = OMIT,
        q: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[EvaluatorRunLaunchResponse]:
        """
        Run evaluators on task items as a background job

        Parameters
        ----------
        task_uuid : str
            Annotation task to act on

        evaluators : typing.Sequence[EvaluatorRunRequestEntry]
            The evaluators to run. Each must be linked to the task

        item_ids : typing.Optional[typing.Sequence[str]]
            Item IDs to run on. **Required when `select_all=false`**. Ignored when `select_all=true`

        select_all : typing.Optional[bool]
            When `true`, run on every item in the task. Set `q` to run only items whose name matches it

        q : typing.Optional[str]
            Case-insensitive substring filter on `payload.name`. Applies only when `select_all=true`

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[EvaluatorRunLaunchResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"annotation-tasks/{encode_path_param(task_uuid)}/evaluator-runs",
            method="POST",
            json={
                "evaluators": convert_and_respect_annotation_metadata(
                    object_=evaluators, annotation=typing.Sequence[EvaluatorRunRequestEntry], direction="write"
                ),
                "item_ids": item_ids,
                "select_all": select_all,
                "q": q,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    EvaluatorRunLaunchResponse,
                    parse_obj_as(
                        type_=EvaluatorRunLaunchResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get_evaluator_run(
        self, task_uuid: str, job_uuid: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[EvaluatorRunResponse]:
        """
        Get one evaluator-run job with results and human-agreement summary

        Parameters
        ----------
        task_uuid : str
            Annotation task to act on

        job_uuid : str
            The evaluator run to act on

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[EvaluatorRunResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"annotation-tasks/{encode_path_param(task_uuid)}/evaluator-runs/{encode_path_param(job_uuid)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    EvaluatorRunResponse,
                    parse_obj_as(
                        type_=EvaluatorRunResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get_agreement(
        self,
        task_uuid: str,
        *,
        bucket: typing.Optional[GetAgreementAnnotationTasksRequestBucket] = None,
        days: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[TaskAgreementResponse]:
        """
        Get human-vs-human and human-vs-evaluator agreement metrics for a task

        Parameters
        ----------
        task_uuid : str
            Annotation task to act on

        bucket : typing.Optional[GetAgreementAnnotationTasksRequestBucket]
            How to bucket points in the trend series

        days : typing.Optional[int]
            Trailing window in days for the trend series

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[TaskAgreementResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"annotation-tasks/{encode_path_param(task_uuid)}/agreement",
            method="GET",
            params={
                "bucket": bucket,
                "days": days,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    TaskAgreementResponse,
                    parse_obj_as(
                        type_=TaskAgreementResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get_summary(
        self,
        task_uuid: str,
        *,
        item_id: typing.Optional[str] = None,
        live_only: typing.Optional[bool] = None,
        q: typing.Optional[str] = None,
        sort_by: typing.Optional[str] = None,
        order: typing.Optional[GetSummaryAnnotationTasksRequestOrder] = None,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[TaskSummaryResponse]:
        """
        Get a paginated summary table of items, evaluator runs, and human annotations for a task

        Parameters
        ----------
        task_uuid : str
            Annotation task to act on

        item_id : typing.Optional[str]
            Filter rows to a single item. The full task-wide annotator union is still returned in `annotators`

        live_only : typing.Optional[bool]
            When true, emit only one row for each (item, evaluator) pair using the evaluator's live version. Versions other than the live one that have runs are excluded

        q : typing.Optional[str]
            Case-insensitive substring search on `payload.name`. Blank is a no-op

        sort_by : typing.Optional[str]
            Sort key for the results

        order : typing.Optional[GetSummaryAnnotationTasksRequestOrder]
            Sort direction

        limit : typing.Optional[int]
            Maximum number of items to return

        offset : typing.Optional[int]
            Number of items to skip before returning results

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[TaskSummaryResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"annotation-tasks/{encode_path_param(task_uuid)}/summary",
            method="GET",
            params={
                "item_id": item_id,
                "live_only": live_only,
                "q": q,
                "sort_by": sort_by,
                "order": order,
                "limit": limit,
                "offset": offset,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    TaskSummaryResponse,
                    parse_obj_as(
                        type_=TaskSummaryResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawAnnotationTasksClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list(
        self,
        *,
        q: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[PaginatedResponseAnnotationTaskResponse]:
        """
        List annotation tasks with linked evaluators

        Parameters
        ----------
        q : typing.Optional[str]
            Case-insensitive substring search on `name`. Blank is a no-op

        limit : typing.Optional[int]
            Maximum number of items to return. Omit for no limit (all items)

        offset : typing.Optional[int]
            Number of items to skip before returning results

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[PaginatedResponseAnnotationTaskResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            "annotation-tasks",
            method="GET",
            params={
                "q": q,
                "limit": limit,
                "offset": offset,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PaginatedResponseAnnotationTaskResponse,
                    parse_obj_as(
                        type_=PaginatedResponseAnnotationTaskResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def create(
        self,
        *,
        name: str,
        type: AnnotationTaskCreateType,
        description: typing.Optional[str] = OMIT,
        evaluator_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[AnnotationTaskCreateResponse]:
        """
        Create an annotation task for annotators to label items against evaluators

        Parameters
        ----------
        name : str
            Task name, unique within your workspace

        type : AnnotationTaskCreateType
            Task type. Determines the shape of each item's payload.
            - `stt`: judge a transcript on its own
            - `llm`: judge one response with its conversation history
            - `llm-general`: judge a standalone `input -> output` pair
            - `conversation`: judge a full conversation

        description : typing.Optional[str]
            A description for the task. Omit for none

        evaluator_ids : typing.Optional[typing.Sequence[str]]
            IDs of evaluators to link when the task is created, in order. Each must be one you created or a built-in default. Omit to create with no linked evaluators

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[AnnotationTaskCreateResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            "annotation-tasks",
            method="POST",
            json={
                "name": name,
                "type": type,
                "description": description,
                "evaluator_ids": evaluator_ids,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    AnnotationTaskCreateResponse,
                    parse_obj_as(
                        type_=AnnotationTaskCreateResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get(
        self, task_uuid: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[AnnotationTaskResponse]:
        """
        Get one annotation task with linked evaluators, items, and labelling jobs

        Parameters
        ----------
        task_uuid : str
            Task to retrieve

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[AnnotationTaskResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"annotation-tasks/{encode_path_param(task_uuid)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    AnnotationTaskResponse,
                    parse_obj_as(
                        type_=AnnotationTaskResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def link_evaluator(
        self, task_uuid: str, *, evaluator_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[EvaluatorLinkResponse]:
        """
        Link an evaluator to a task, appending it to the display order

        Parameters
        ----------
        task_uuid : str
            Annotation task to act on

        evaluator_id : str
            The evaluator to link. Must be one you created or a built-in default

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[EvaluatorLinkResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"annotation-tasks/{encode_path_param(task_uuid)}/evaluators",
            method="POST",
            json={
                "evaluator_id": evaluator_id,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    EvaluatorLinkResponse,
                    parse_obj_as(
                        type_=EvaluatorLinkResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def add_items(
        self,
        task_uuid: str,
        *,
        items: typing.Sequence[AnnotationItemPayload],
        annotator_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[BulkCreateItemsResponse]:
        """
        Bulk-create annotation items in a task, optionally seeding human annotations

        Parameters
        ----------
        task_uuid : str
            Annotation task to act on

        items : typing.Sequence[AnnotationItemPayload]
            Items to insert. Insertion order is preserved

        annotator_id : typing.Optional[str]
            Annotator these initial annotations belong to. Required when any item carries annotations

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[BulkCreateItemsResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"annotation-tasks/{encode_path_param(task_uuid)}/items",
            method="POST",
            json={
                "items": convert_and_respect_annotation_metadata(
                    object_=items, annotation=typing.Sequence[AnnotationItemPayload], direction="write"
                ),
                "annotator_id": annotator_id,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    BulkCreateItemsResponse,
                    parse_obj_as(
                        type_=BulkCreateItemsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def update_items(
        self,
        task_uuid: str,
        *,
        updates: typing.Sequence[ItemUpdatePayload],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[BulkUpdateItemsResponse]:
        """
        Bulk-update item payloads in a task

        Parameters
        ----------
        task_uuid : str
            Annotation task to act on

        updates : typing.Sequence[ItemUpdatePayload]
            The new payload for each item you're updating. Entries not in this task, or referencing deleted items, are skipped

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[BulkUpdateItemsResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"annotation-tasks/{encode_path_param(task_uuid)}/items",
            method="PUT",
            json={
                "updates": convert_and_respect_annotation_metadata(
                    object_=updates, annotation=typing.Sequence[ItemUpdatePayload], direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    BulkUpdateItemsResponse,
                    parse_obj_as(
                        type_=BulkUpdateItemsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def create_evaluator_run(
        self,
        task_uuid: str,
        *,
        evaluators: typing.Sequence[EvaluatorRunRequestEntry],
        item_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        select_all: typing.Optional[bool] = OMIT,
        q: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[EvaluatorRunLaunchResponse]:
        """
        Run evaluators on task items as a background job

        Parameters
        ----------
        task_uuid : str
            Annotation task to act on

        evaluators : typing.Sequence[EvaluatorRunRequestEntry]
            The evaluators to run. Each must be linked to the task

        item_ids : typing.Optional[typing.Sequence[str]]
            Item IDs to run on. **Required when `select_all=false`**. Ignored when `select_all=true`

        select_all : typing.Optional[bool]
            When `true`, run on every item in the task. Set `q` to run only items whose name matches it

        q : typing.Optional[str]
            Case-insensitive substring filter on `payload.name`. Applies only when `select_all=true`

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[EvaluatorRunLaunchResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"annotation-tasks/{encode_path_param(task_uuid)}/evaluator-runs",
            method="POST",
            json={
                "evaluators": convert_and_respect_annotation_metadata(
                    object_=evaluators, annotation=typing.Sequence[EvaluatorRunRequestEntry], direction="write"
                ),
                "item_ids": item_ids,
                "select_all": select_all,
                "q": q,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    EvaluatorRunLaunchResponse,
                    parse_obj_as(
                        type_=EvaluatorRunLaunchResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get_evaluator_run(
        self, task_uuid: str, job_uuid: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[EvaluatorRunResponse]:
        """
        Get one evaluator-run job with results and human-agreement summary

        Parameters
        ----------
        task_uuid : str
            Annotation task to act on

        job_uuid : str
            The evaluator run to act on

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[EvaluatorRunResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"annotation-tasks/{encode_path_param(task_uuid)}/evaluator-runs/{encode_path_param(job_uuid)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    EvaluatorRunResponse,
                    parse_obj_as(
                        type_=EvaluatorRunResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get_agreement(
        self,
        task_uuid: str,
        *,
        bucket: typing.Optional[GetAgreementAnnotationTasksRequestBucket] = None,
        days: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[TaskAgreementResponse]:
        """
        Get human-vs-human and human-vs-evaluator agreement metrics for a task

        Parameters
        ----------
        task_uuid : str
            Annotation task to act on

        bucket : typing.Optional[GetAgreementAnnotationTasksRequestBucket]
            How to bucket points in the trend series

        days : typing.Optional[int]
            Trailing window in days for the trend series

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[TaskAgreementResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"annotation-tasks/{encode_path_param(task_uuid)}/agreement",
            method="GET",
            params={
                "bucket": bucket,
                "days": days,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    TaskAgreementResponse,
                    parse_obj_as(
                        type_=TaskAgreementResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get_summary(
        self,
        task_uuid: str,
        *,
        item_id: typing.Optional[str] = None,
        live_only: typing.Optional[bool] = None,
        q: typing.Optional[str] = None,
        sort_by: typing.Optional[str] = None,
        order: typing.Optional[GetSummaryAnnotationTasksRequestOrder] = None,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[TaskSummaryResponse]:
        """
        Get a paginated summary table of items, evaluator runs, and human annotations for a task

        Parameters
        ----------
        task_uuid : str
            Annotation task to act on

        item_id : typing.Optional[str]
            Filter rows to a single item. The full task-wide annotator union is still returned in `annotators`

        live_only : typing.Optional[bool]
            When true, emit only one row for each (item, evaluator) pair using the evaluator's live version. Versions other than the live one that have runs are excluded

        q : typing.Optional[str]
            Case-insensitive substring search on `payload.name`. Blank is a no-op

        sort_by : typing.Optional[str]
            Sort key for the results

        order : typing.Optional[GetSummaryAnnotationTasksRequestOrder]
            Sort direction

        limit : typing.Optional[int]
            Maximum number of items to return

        offset : typing.Optional[int]
            Number of items to skip before returning results

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[TaskSummaryResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"annotation-tasks/{encode_path_param(task_uuid)}/summary",
            method="GET",
            params={
                "item_id": item_id,
                "live_only": live_only,
                "q": q,
                "sort_by": sort_by,
                "order": order,
                "limit": limit,
                "offset": offset,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    TaskSummaryResponse,
                    parse_obj_as(
                        type_=TaskSummaryResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
