# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.resolve_agent_names_response import ResolveAgentNamesResponse
from ..types.routers_agent_tools_agent_response import RoutersAgentToolsAgentResponse
from .raw_client import AsyncRawAgentsClient, RawAgentsClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class AgentsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawAgentsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawAgentsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawAgentsClient
        """
        return self._raw_client

    def resolve(
        self, *, names: typing.Sequence[str], request_options: typing.Optional[RequestOptions] = None
    ) -> ResolveAgentNamesResponse:
        """
        Resolve a list of agent names to their UUIDs within the caller's org.

        Auth accepts either a JWT (frontend) or an `sk_` API key (programmatic
        clients) via `get_org_jwt_or_api_key`, so CI tooling can map human-friendly
        agent names to the UUIDs the run/poll endpoints expect. Agent names are
        unique per org, so each name resolves to at most one agent. Names with no
        matching (non-deleted) agent in the org are returned under `not_found`.

        Parameters
        ----------
        names : typing.Sequence[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ResolveAgentNamesResponse
            Successful Response

        Examples
        --------
        from calibrate import Calibrate

        client = Calibrate(
            org_uuid="YOUR_ORG_UUID",
            api_key="YOUR_API_KEY",
        )
        client.agents.resolve(
            names=["names"],
        )
        """
        _response = self._raw_client.resolve(names=names, request_options=request_options)
        return _response.data

    def list(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[RoutersAgentToolsAgentResponse]:
        """
        List all agents for the caller's current org.

        Auth accepts either a JWT (frontend) or an `sk_` API key (programmatic
        clients) via `get_org_jwt_or_api_key`, so CI tooling can enumerate every
        agent UUID in the org without knowing names up front (the run/poll and
        `/resolve` endpoints accept the same key).

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[RoutersAgentToolsAgentResponse]
            Successful Response

        Examples
        --------
        from calibrate import Calibrate

        client = Calibrate(
            org_uuid="YOUR_ORG_UUID",
            api_key="YOUR_API_KEY",
        )
        client.agents.list()
        """
        _response = self._raw_client.list(request_options=request_options)
        return _response.data


class AsyncAgentsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawAgentsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawAgentsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawAgentsClient
        """
        return self._raw_client

    async def resolve(
        self, *, names: typing.Sequence[str], request_options: typing.Optional[RequestOptions] = None
    ) -> ResolveAgentNamesResponse:
        """
        Resolve a list of agent names to their UUIDs within the caller's org.

        Auth accepts either a JWT (frontend) or an `sk_` API key (programmatic
        clients) via `get_org_jwt_or_api_key`, so CI tooling can map human-friendly
        agent names to the UUIDs the run/poll endpoints expect. Agent names are
        unique per org, so each name resolves to at most one agent. Names with no
        matching (non-deleted) agent in the org are returned under `not_found`.

        Parameters
        ----------
        names : typing.Sequence[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ResolveAgentNamesResponse
            Successful Response

        Examples
        --------
        import asyncio

        from calibrate import AsyncCalibrate

        client = AsyncCalibrate(
            org_uuid="YOUR_ORG_UUID",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.agents.resolve(
                names=["names"],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.resolve(names=names, request_options=request_options)
        return _response.data

    async def list(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[RoutersAgentToolsAgentResponse]:
        """
        List all agents for the caller's current org.

        Auth accepts either a JWT (frontend) or an `sk_` API key (programmatic
        clients) via `get_org_jwt_or_api_key`, so CI tooling can enumerate every
        agent UUID in the org without knowing names up front (the run/poll and
        `/resolve` endpoints accept the same key).

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[RoutersAgentToolsAgentResponse]
            Successful Response

        Examples
        --------
        import asyncio

        from calibrate import AsyncCalibrate

        client = AsyncCalibrate(
            org_uuid="YOUR_ORG_UUID",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.agents.list()


        asyncio.run(main())
        """
        _response = await self._raw_client.list(request_options=request_options)
        return _response.data
