# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.agent_create_response import AgentCreateResponse
from ..types.paginated_response_agent_summary import PaginatedResponseAgentSummary
from ..types.resolve_agent_names_response import ResolveAgentNamesResponse
from ..types.routers_agents_agent_response import RoutersAgentsAgentResponse
from ..types.verify_connection_response import VerifyConnectionResponse
from .raw_client import AsyncRawAgentsClient, RawAgentsClient
from .types.agent_create_type import AgentCreateType

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class AgentsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawAgentsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawAgentsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawAgentsClient
        """
        return self._raw_client

    def verify_connection(
        self,
        agent_uuid: str,
        *,
        model: typing.Optional[str] = OMIT,
        messages: typing.Optional[typing.Sequence[typing.Dict[str, str]]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> VerifyConnectionResponse:
        """
        Verify an agent's connection and persist the result when successful

        Parameters
        ----------
        agent_uuid : str
            The agent whose connection to verify

        model : typing.Optional[str]
            Model to verify. Omit for a basic connection check. Provide it for a model-specific check before benchmarking that model

        messages : typing.Optional[typing.Sequence[typing.Dict[str, str]]]
            Sample chat messages to send during verification. Omit to use the default probe

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        VerifyConnectionResponse
            Successful Response

        Examples
        --------
        from calibrate import Calibrate

        client = Calibrate(
            api_key="YOUR_API_KEY",
        )
        client.agents.verify_connection(
            agent_uuid="f47ac10b-58cc-4372-a567-0e02b2c3d479",
        )
        """
        _response = self._raw_client.verify_connection(
            agent_uuid, model=model, messages=messages, request_options=request_options
        )
        return _response.data

    def resolve(
        self, *, names: typing.Sequence[str], request_options: typing.Optional[RequestOptions] = None
    ) -> ResolveAgentNamesResponse:
        """
        Get the IDs for your agents by their names

        Parameters
        ----------
        names : typing.Sequence[str]
            Agent names to resolve to IDs

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ResolveAgentNamesResponse
            Successful Response

        Examples
        --------
        from calibrate import Calibrate

        client = Calibrate(
            api_key="YOUR_API_KEY",
        )
        client.agents.resolve(
            names=["my-agent", "support-bot"],
        )
        """
        _response = self._raw_client.resolve(names=names, request_options=request_options)
        return _response.data

    def list(
        self,
        *,
        q: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PaginatedResponseAgentSummary:
        """
        Get the list of all your agents

        Parameters
        ----------
        q : typing.Optional[str]
            Case-insensitive substring search on `name`. Blank is a no-op

        limit : typing.Optional[int]
            Maximum number of items to return. Omit for no limit (all items)

        offset : typing.Optional[int]
            Number of items to skip before returning results

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PaginatedResponseAgentSummary
            Successful Response

        Examples
        --------
        from calibrate import Calibrate

        client = Calibrate(
            api_key="YOUR_API_KEY",
        )
        client.agents.list()
        """
        _response = self._raw_client.list(q=q, limit=limit, offset=offset, request_options=request_options)
        return _response.data

    def create(
        self,
        *,
        name: str,
        type: typing.Optional[AgentCreateType] = OMIT,
        config: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AgentCreateResponse:
        """
        Create an agent to test inside Calibrate or connect your existing agent to Calibrate

        Parameters
        ----------
        name : str
            Agent name, unique within the workspace

        type : typing.Optional[AgentCreateType]
            - `agent`: built inside Calibrate
            - `connection`: your existing agent connected to Calibrate

        config : typing.Optional[typing.Dict[str, typing.Any]]
            Agent behavioral config. The keys depend on `type`.

            **`type=agent`**, built inside Calibrate:
            - `system_prompt`: the agent's instructions
            - `llm.model`: `provider/model`, e.g. `openai/gpt-4.1` or `google/gemini-2.5-flash`
            - `stt.provider`: `deepgram`, `openai`, `cartesia`, `elevenlabs`, `google`, `sarvam`, or `smallest`
            - `tts.provider`: `cartesia`, `openai`, `google`, `elevenlabs`, `sarvam`, or `smallest`
            - `settings.agent_speaks_first`, `settings.max_assistant_turns`
            - `system_tools.end_call`: let the agent end the call
            - `data_extraction_fields`: `[{name, type, description, required}]`

            ```json
            {
              "system_prompt": "You are a helpful support agent.",
              "llm": {"model": "openai/gpt-4.1"},
              "stt": {"provider": "deepgram"},
              "tts": {"provider": "elevenlabs"},
              "settings": {"agent_speaks_first": true, "max_assistant_turns": 50}
            }
            ```

            **`type=connection`**, your own HTTP endpoint:
            - `agent_url`: public HTTP(S) endpoint your agent is called at
            - `agent_headers`: headers sent on each request, e.g. auth
            - `benchmark_provider`: `openrouter` by default. Other values: `openai`, `google`, `anthropic`, `meta-llama`, `mistralai`, `deepseek`, `x-ai`, `cohere`, `qwen`, or `ai21`

            ```json
            {
              "agent_url": "https://api.example.com/agent",
              "agent_headers": {"Authorization": "Bearer <token>"},
              "benchmark_provider": "openrouter"
            }
            ```

            For `type=agent`, omitted keys inherit managed defaults. Omit `config` entirely to use all defaults. For `type=connection`, `config` is stored as-is and must contain `agent_url`

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AgentCreateResponse
            Successful Response

        Examples
        --------
        from calibrate import Calibrate

        client = Calibrate(
            api_key="YOUR_API_KEY",
        )
        client.agents.create(
            name="Support Agent",
            type="agent",
            config={
                "system_prompt": "You are a helpful assistant.",
                "llm": {"model": "google/gemini-2.5-flash"},
                "stt": {"provider": "google"},
                "tts": {"provider": "google"},
                "settings": {"agent_speaks_first": True, "max_assistant_turns": 50},
            },
        )
        """
        _response = self._raw_client.create(name=name, type=type, config=config, request_options=request_options)
        return _response.data

    def get(
        self, agent_uuid: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> RoutersAgentsAgentResponse:
        """
        Get one agent by its ID

        Parameters
        ----------
        agent_uuid : str
            The agent to retrieve

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RoutersAgentsAgentResponse
            Successful Response

        Examples
        --------
        from calibrate import Calibrate

        client = Calibrate(
            api_key="YOUR_API_KEY",
        )
        client.agents.get(
            agent_uuid="f47ac10b-58cc-4372-a567-0e02b2c3d479",
        )
        """
        _response = self._raw_client.get(agent_uuid, request_options=request_options)
        return _response.data

    def update(
        self,
        agent_uuid: str,
        *,
        name: typing.Optional[str] = OMIT,
        config: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> RoutersAgentsAgentResponse:
        """
        Update an agent's configuration

        Parameters
        ----------
        agent_uuid : str
            The agent to update

        name : typing.Optional[str]
            New agent name. Omit to leave the name unchanged

        config : typing.Optional[typing.Dict[str, typing.Any]]
            Agent behavioral config. The keys depend on `type`.

            **`type=agent`**, built inside Calibrate:
            - `system_prompt`: the agent's instructions
            - `llm.model`: `provider/model`, e.g. `openai/gpt-4.1` or `google/gemini-2.5-flash`
            - `stt.provider`: `deepgram`, `openai`, `cartesia`, `elevenlabs`, `google`, `sarvam`, or `smallest`
            - `tts.provider`: `cartesia`, `openai`, `google`, `elevenlabs`, `sarvam`, or `smallest`
            - `settings.agent_speaks_first`, `settings.max_assistant_turns`
            - `system_tools.end_call`: let the agent end the call
            - `data_extraction_fields`: `[{name, type, description, required}]`

            ```json
            {
              "system_prompt": "You are a helpful support agent.",
              "llm": {"model": "openai/gpt-4.1"},
              "stt": {"provider": "deepgram"},
              "tts": {"provider": "elevenlabs"},
              "settings": {"agent_speaks_first": true, "max_assistant_turns": 50}
            }
            ```

            **`type=connection`**, your own HTTP endpoint:
            - `agent_url`: public HTTP(S) endpoint your agent is called at
            - `agent_headers`: headers sent on each request, e.g. auth
            - `benchmark_provider`: `openrouter` by default. Other values: `openai`, `google`, `anthropic`, `meta-llama`, `mistralai`, `deepseek`, `x-ai`, `cohere`, `qwen`, or `ai21`

            ```json
            {
              "agent_url": "https://api.example.com/agent",
              "agent_headers": {"Authorization": "Bearer <token>"},
              "benchmark_provider": "openrouter"
            }
            ```

            Replaces the stored config. Omit to leave unchanged

            For `type=connection`, changing `agent_url` or `agent_headers` resets the connection and benchmark verification flags

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RoutersAgentsAgentResponse
            Successful Response

        Examples
        --------
        from calibrate import Calibrate

        client = Calibrate(
            api_key="YOUR_API_KEY",
        )
        client.agents.update(
            agent_uuid="f47ac10b-58cc-4372-a567-0e02b2c3d479",
        )
        """
        _response = self._raw_client.update(agent_uuid, name=name, config=config, request_options=request_options)
        return _response.data


class AsyncAgentsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawAgentsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawAgentsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawAgentsClient
        """
        return self._raw_client

    async def verify_connection(
        self,
        agent_uuid: str,
        *,
        model: typing.Optional[str] = OMIT,
        messages: typing.Optional[typing.Sequence[typing.Dict[str, str]]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> VerifyConnectionResponse:
        """
        Verify an agent's connection and persist the result when successful

        Parameters
        ----------
        agent_uuid : str
            The agent whose connection to verify

        model : typing.Optional[str]
            Model to verify. Omit for a basic connection check. Provide it for a model-specific check before benchmarking that model

        messages : typing.Optional[typing.Sequence[typing.Dict[str, str]]]
            Sample chat messages to send during verification. Omit to use the default probe

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        VerifyConnectionResponse
            Successful Response

        Examples
        --------
        import asyncio

        from calibrate import AsyncCalibrate

        client = AsyncCalibrate(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.agents.verify_connection(
                agent_uuid="f47ac10b-58cc-4372-a567-0e02b2c3d479",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.verify_connection(
            agent_uuid, model=model, messages=messages, request_options=request_options
        )
        return _response.data

    async def resolve(
        self, *, names: typing.Sequence[str], request_options: typing.Optional[RequestOptions] = None
    ) -> ResolveAgentNamesResponse:
        """
        Get the IDs for your agents by their names

        Parameters
        ----------
        names : typing.Sequence[str]
            Agent names to resolve to IDs

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ResolveAgentNamesResponse
            Successful Response

        Examples
        --------
        import asyncio

        from calibrate import AsyncCalibrate

        client = AsyncCalibrate(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.agents.resolve(
                names=["my-agent", "support-bot"],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.resolve(names=names, request_options=request_options)
        return _response.data

    async def list(
        self,
        *,
        q: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PaginatedResponseAgentSummary:
        """
        Get the list of all your agents

        Parameters
        ----------
        q : typing.Optional[str]
            Case-insensitive substring search on `name`. Blank is a no-op

        limit : typing.Optional[int]
            Maximum number of items to return. Omit for no limit (all items)

        offset : typing.Optional[int]
            Number of items to skip before returning results

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PaginatedResponseAgentSummary
            Successful Response

        Examples
        --------
        import asyncio

        from calibrate import AsyncCalibrate

        client = AsyncCalibrate(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.agents.list()


        asyncio.run(main())
        """
        _response = await self._raw_client.list(q=q, limit=limit, offset=offset, request_options=request_options)
        return _response.data

    async def create(
        self,
        *,
        name: str,
        type: typing.Optional[AgentCreateType] = OMIT,
        config: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AgentCreateResponse:
        """
        Create an agent to test inside Calibrate or connect your existing agent to Calibrate

        Parameters
        ----------
        name : str
            Agent name, unique within the workspace

        type : typing.Optional[AgentCreateType]
            - `agent`: built inside Calibrate
            - `connection`: your existing agent connected to Calibrate

        config : typing.Optional[typing.Dict[str, typing.Any]]
            Agent behavioral config. The keys depend on `type`.

            **`type=agent`**, built inside Calibrate:
            - `system_prompt`: the agent's instructions
            - `llm.model`: `provider/model`, e.g. `openai/gpt-4.1` or `google/gemini-2.5-flash`
            - `stt.provider`: `deepgram`, `openai`, `cartesia`, `elevenlabs`, `google`, `sarvam`, or `smallest`
            - `tts.provider`: `cartesia`, `openai`, `google`, `elevenlabs`, `sarvam`, or `smallest`
            - `settings.agent_speaks_first`, `settings.max_assistant_turns`
            - `system_tools.end_call`: let the agent end the call
            - `data_extraction_fields`: `[{name, type, description, required}]`

            ```json
            {
              "system_prompt": "You are a helpful support agent.",
              "llm": {"model": "openai/gpt-4.1"},
              "stt": {"provider": "deepgram"},
              "tts": {"provider": "elevenlabs"},
              "settings": {"agent_speaks_first": true, "max_assistant_turns": 50}
            }
            ```

            **`type=connection`**, your own HTTP endpoint:
            - `agent_url`: public HTTP(S) endpoint your agent is called at
            - `agent_headers`: headers sent on each request, e.g. auth
            - `benchmark_provider`: `openrouter` by default. Other values: `openai`, `google`, `anthropic`, `meta-llama`, `mistralai`, `deepseek`, `x-ai`, `cohere`, `qwen`, or `ai21`

            ```json
            {
              "agent_url": "https://api.example.com/agent",
              "agent_headers": {"Authorization": "Bearer <token>"},
              "benchmark_provider": "openrouter"
            }
            ```

            For `type=agent`, omitted keys inherit managed defaults. Omit `config` entirely to use all defaults. For `type=connection`, `config` is stored as-is and must contain `agent_url`

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AgentCreateResponse
            Successful Response

        Examples
        --------
        import asyncio

        from calibrate import AsyncCalibrate

        client = AsyncCalibrate(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.agents.create(
                name="Support Agent",
                type="agent",
                config={
                    "system_prompt": "You are a helpful assistant.",
                    "llm": {"model": "google/gemini-2.5-flash"},
                    "stt": {"provider": "google"},
                    "tts": {"provider": "google"},
                    "settings": {"agent_speaks_first": True, "max_assistant_turns": 50},
                },
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(name=name, type=type, config=config, request_options=request_options)
        return _response.data

    async def get(
        self, agent_uuid: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> RoutersAgentsAgentResponse:
        """
        Get one agent by its ID

        Parameters
        ----------
        agent_uuid : str
            The agent to retrieve

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RoutersAgentsAgentResponse
            Successful Response

        Examples
        --------
        import asyncio

        from calibrate import AsyncCalibrate

        client = AsyncCalibrate(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.agents.get(
                agent_uuid="f47ac10b-58cc-4372-a567-0e02b2c3d479",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(agent_uuid, request_options=request_options)
        return _response.data

    async def update(
        self,
        agent_uuid: str,
        *,
        name: typing.Optional[str] = OMIT,
        config: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> RoutersAgentsAgentResponse:
        """
        Update an agent's configuration

        Parameters
        ----------
        agent_uuid : str
            The agent to update

        name : typing.Optional[str]
            New agent name. Omit to leave the name unchanged

        config : typing.Optional[typing.Dict[str, typing.Any]]
            Agent behavioral config. The keys depend on `type`.

            **`type=agent`**, built inside Calibrate:
            - `system_prompt`: the agent's instructions
            - `llm.model`: `provider/model`, e.g. `openai/gpt-4.1` or `google/gemini-2.5-flash`
            - `stt.provider`: `deepgram`, `openai`, `cartesia`, `elevenlabs`, `google`, `sarvam`, or `smallest`
            - `tts.provider`: `cartesia`, `openai`, `google`, `elevenlabs`, `sarvam`, or `smallest`
            - `settings.agent_speaks_first`, `settings.max_assistant_turns`
            - `system_tools.end_call`: let the agent end the call
            - `data_extraction_fields`: `[{name, type, description, required}]`

            ```json
            {
              "system_prompt": "You are a helpful support agent.",
              "llm": {"model": "openai/gpt-4.1"},
              "stt": {"provider": "deepgram"},
              "tts": {"provider": "elevenlabs"},
              "settings": {"agent_speaks_first": true, "max_assistant_turns": 50}
            }
            ```

            **`type=connection`**, your own HTTP endpoint:
            - `agent_url`: public HTTP(S) endpoint your agent is called at
            - `agent_headers`: headers sent on each request, e.g. auth
            - `benchmark_provider`: `openrouter` by default. Other values: `openai`, `google`, `anthropic`, `meta-llama`, `mistralai`, `deepseek`, `x-ai`, `cohere`, `qwen`, or `ai21`

            ```json
            {
              "agent_url": "https://api.example.com/agent",
              "agent_headers": {"Authorization": "Bearer <token>"},
              "benchmark_provider": "openrouter"
            }
            ```

            Replaces the stored config. Omit to leave unchanged

            For `type=connection`, changing `agent_url` or `agent_headers` resets the connection and benchmark verification flags

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RoutersAgentsAgentResponse
            Successful Response

        Examples
        --------
        import asyncio

        from calibrate import AsyncCalibrate

        client = AsyncCalibrate(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.agents.update(
                agent_uuid="f47ac10b-58cc-4372-a567-0e02b2c3d479",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update(agent_uuid, name=name, config=config, request_options=request_options)
        return _response.data
