# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..errors.unprocessable_entity_error import UnprocessableEntityError
from ..types.http_validation_error import HttpValidationError
from ..types.resolve_agent_names_response import ResolveAgentNamesResponse
from ..types.routers_agent_tools_agent_response import RoutersAgentToolsAgentResponse
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawAgentsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def resolve(
        self, *, names: typing.Sequence[str], request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[ResolveAgentNamesResponse]:
        """
        Resolve a list of agent names to their UUIDs within the caller's org.

        Auth accepts either a JWT (frontend) or an `sk_` API key (programmatic
        clients) via `get_org_jwt_or_api_key`, so CI tooling can map human-friendly
        agent names to the UUIDs the run/poll endpoints expect. Agent names are
        unique per org, so each name resolves to at most one agent. Names with no
        matching (non-deleted) agent in the org are returned under `not_found`.

        Parameters
        ----------
        names : typing.Sequence[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ResolveAgentNamesResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            "agents/resolve",
            method="POST",
            json={
                "names": names,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ResolveAgentNamesResponse,
                    parse_obj_as(
                        type_=ResolveAgentNamesResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def list(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[typing.List[RoutersAgentToolsAgentResponse]]:
        """
        List all agents for the caller's current org.

        Auth accepts either a JWT (frontend) or an `sk_` API key (programmatic
        clients) via `get_org_jwt_or_api_key`, so CI tooling can enumerate every
        agent UUID in the org without knowing names up front (the run/poll and
        `/resolve` endpoints accept the same key).

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[typing.List[RoutersAgentToolsAgentResponse]]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            "agents",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.List[RoutersAgentToolsAgentResponse],
                    parse_obj_as(
                        type_=typing.List[RoutersAgentToolsAgentResponse],  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawAgentsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def resolve(
        self, *, names: typing.Sequence[str], request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[ResolveAgentNamesResponse]:
        """
        Resolve a list of agent names to their UUIDs within the caller's org.

        Auth accepts either a JWT (frontend) or an `sk_` API key (programmatic
        clients) via `get_org_jwt_or_api_key`, so CI tooling can map human-friendly
        agent names to the UUIDs the run/poll endpoints expect. Agent names are
        unique per org, so each name resolves to at most one agent. Names with no
        matching (non-deleted) agent in the org are returned under `not_found`.

        Parameters
        ----------
        names : typing.Sequence[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ResolveAgentNamesResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            "agents/resolve",
            method="POST",
            json={
                "names": names,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ResolveAgentNamesResponse,
                    parse_obj_as(
                        type_=ResolveAgentNamesResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def list(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[typing.List[RoutersAgentToolsAgentResponse]]:
        """
        List all agents for the caller's current org.

        Auth accepts either a JWT (frontend) or an `sk_` API key (programmatic
        clients) via `get_org_jwt_or_api_key`, so CI tooling can enumerate every
        agent UUID in the org without knowing names up front (the run/poll and
        `/resolve` endpoints accept the same key).

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[typing.List[RoutersAgentToolsAgentResponse]]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            "agents",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.List[RoutersAgentToolsAgentResponse],
                    parse_obj_as(
                        type_=typing.List[RoutersAgentToolsAgentResponse],  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
