# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import encode_path_param
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..core.serialization import convert_and_respect_annotation_metadata
from ..errors.unprocessable_entity_error import UnprocessableEntityError
from ..types.bulk_test_item import BulkTestItem
from ..types.bulk_test_upload_response import BulkTestUploadResponse
from ..types.http_validation_error import HttpValidationError
from ..types.routers_tests_evaluator_ref import RoutersTestsEvaluatorRef
from ..types.routers_tests_test_response import RoutersTestsTestResponse
from ..types.test_create_response import TestCreateResponse
from .types.bulk_test_upload_type import BulkTestUploadType
from .types.test_create_type import TestCreateType
from .types.test_update_type import TestUpdateType
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawTestsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def bulk_create(
        self,
        *,
        type: BulkTestUploadType,
        tests: typing.Sequence[BulkTestItem],
        agent_uuids: typing.Optional[typing.Sequence[str]] = OMIT,
        language: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[BulkTestUploadResponse]:
        """
        Create many tests of one type in a single call, optionally linking them to agents.

        Parameters
        ----------
        type : BulkTestUploadType
            Test kind applied to every item in the batch

        tests : typing.Sequence[BulkTestItem]
            Test items to create (non-empty, max 500 per request, names unique within the batch)

        agent_uuids : typing.Optional[typing.Sequence[str]]
            Agents (IDs) to link every created test to. Omit to link none

        language : typing.Optional[str]
            Language written to each test's `config.settings.language`. Omit to leave unset

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[BulkTestUploadResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            "tests/bulk",
            method="POST",
            json={
                "type": type,
                "tests": convert_and_respect_annotation_metadata(
                    object_=tests, annotation=typing.Sequence[BulkTestItem], direction="write"
                ),
                "agent_uuids": agent_uuids,
                "language": language,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    BulkTestUploadResponse,
                    parse_obj_as(
                        type_=BulkTestUploadResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def list(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[typing.List[RoutersTestsTestResponse]]:
        """
        List all tests for your workspace, each with its linked evaluators.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[typing.List[RoutersTestsTestResponse]]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            "tests",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.List[RoutersTestsTestResponse],
                    parse_obj_as(
                        type_=typing.List[RoutersTestsTestResponse],  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def create(
        self,
        *,
        name: str,
        type: TestCreateType,
        config: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        evaluators: typing.Optional[typing.Sequence[RoutersTestsEvaluatorRef]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[TestCreateResponse]:
        """
        Create a test in your workspace.

        Parameters
        ----------
        name : str
            Human-readable test name, unique within the workspace

        type : TestCreateType
            Test kind (immutable after creation): `response` judges the generated reply, `tool_call` diffs generated tool calls, `conversation` judges the full conversation

        config : typing.Optional[typing.Dict[str, typing.Any]]
            Calibrate test config (`history`, `evaluation`, optional `settings`). Omit to create an empty shell to fill in later

        evaluators : typing.Optional[typing.Sequence[RoutersTestsEvaluatorRef]]
            Evaluators to link. **Required (>=1) for `type=conversation`** (no fallback judge). Omit for `response`/`tool_call` to link none

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[TestCreateResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            "tests",
            method="POST",
            json={
                "name": name,
                "type": type,
                "config": config,
                "evaluators": convert_and_respect_annotation_metadata(
                    object_=evaluators,
                    annotation=typing.Optional[typing.Sequence[RoutersTestsEvaluatorRef]],
                    direction="write",
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    TestCreateResponse,
                    parse_obj_as(
                        type_=TestCreateResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get(
        self, test_uuid: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[RoutersTestsTestResponse]:
        """
        Get a test by ID, including its linked evaluators.

        Parameters
        ----------
        test_uuid : str
            Test to retrieve

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[RoutersTestsTestResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"tests/{encode_path_param(test_uuid)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    RoutersTestsTestResponse,
                    parse_obj_as(
                        type_=RoutersTestsTestResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def update(
        self,
        test_uuid: str,
        *,
        name: typing.Optional[str] = OMIT,
        type: typing.Optional[TestUpdateType] = OMIT,
        config: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        evaluators: typing.Optional[typing.Sequence[RoutersTestsEvaluatorRef]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[RoutersTestsTestResponse]:
        """
        Update a test's name, config, and/or evaluator links.

        Parameters
        ----------
        test_uuid : str
            Test to update

        name : typing.Optional[str]
            New test name. Omit to leave unchanged

        type : typing.Optional[TestUpdateType]
            Test type. Immutable — may only echo the existing value; a different value is rejected (400). Omit to leave unchanged

        config : typing.Optional[typing.Dict[str, typing.Any]]
            Replacement calibrate config. Omit to leave unchanged

        evaluators : typing.Optional[typing.Sequence[RoutersTestsEvaluatorRef]]
            Replacement evaluator links (replaces the existing set). Omit to leave links unchanged; an empty list clears them (**rejected for `conversation` tests**)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[RoutersTestsTestResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"tests/{encode_path_param(test_uuid)}",
            method="PUT",
            json={
                "name": name,
                "type": type,
                "config": config,
                "evaluators": convert_and_respect_annotation_metadata(
                    object_=evaluators,
                    annotation=typing.Optional[typing.Sequence[RoutersTestsEvaluatorRef]],
                    direction="write",
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    RoutersTestsTestResponse,
                    parse_obj_as(
                        type_=RoutersTestsTestResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawTestsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def bulk_create(
        self,
        *,
        type: BulkTestUploadType,
        tests: typing.Sequence[BulkTestItem],
        agent_uuids: typing.Optional[typing.Sequence[str]] = OMIT,
        language: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[BulkTestUploadResponse]:
        """
        Create many tests of one type in a single call, optionally linking them to agents.

        Parameters
        ----------
        type : BulkTestUploadType
            Test kind applied to every item in the batch

        tests : typing.Sequence[BulkTestItem]
            Test items to create (non-empty, max 500 per request, names unique within the batch)

        agent_uuids : typing.Optional[typing.Sequence[str]]
            Agents (IDs) to link every created test to. Omit to link none

        language : typing.Optional[str]
            Language written to each test's `config.settings.language`. Omit to leave unset

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[BulkTestUploadResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            "tests/bulk",
            method="POST",
            json={
                "type": type,
                "tests": convert_and_respect_annotation_metadata(
                    object_=tests, annotation=typing.Sequence[BulkTestItem], direction="write"
                ),
                "agent_uuids": agent_uuids,
                "language": language,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    BulkTestUploadResponse,
                    parse_obj_as(
                        type_=BulkTestUploadResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def list(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[typing.List[RoutersTestsTestResponse]]:
        """
        List all tests for your workspace, each with its linked evaluators.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[typing.List[RoutersTestsTestResponse]]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            "tests",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.List[RoutersTestsTestResponse],
                    parse_obj_as(
                        type_=typing.List[RoutersTestsTestResponse],  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def create(
        self,
        *,
        name: str,
        type: TestCreateType,
        config: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        evaluators: typing.Optional[typing.Sequence[RoutersTestsEvaluatorRef]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[TestCreateResponse]:
        """
        Create a test in your workspace.

        Parameters
        ----------
        name : str
            Human-readable test name, unique within the workspace

        type : TestCreateType
            Test kind (immutable after creation): `response` judges the generated reply, `tool_call` diffs generated tool calls, `conversation` judges the full conversation

        config : typing.Optional[typing.Dict[str, typing.Any]]
            Calibrate test config (`history`, `evaluation`, optional `settings`). Omit to create an empty shell to fill in later

        evaluators : typing.Optional[typing.Sequence[RoutersTestsEvaluatorRef]]
            Evaluators to link. **Required (>=1) for `type=conversation`** (no fallback judge). Omit for `response`/`tool_call` to link none

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[TestCreateResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            "tests",
            method="POST",
            json={
                "name": name,
                "type": type,
                "config": config,
                "evaluators": convert_and_respect_annotation_metadata(
                    object_=evaluators,
                    annotation=typing.Optional[typing.Sequence[RoutersTestsEvaluatorRef]],
                    direction="write",
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    TestCreateResponse,
                    parse_obj_as(
                        type_=TestCreateResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get(
        self, test_uuid: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[RoutersTestsTestResponse]:
        """
        Get a test by ID, including its linked evaluators.

        Parameters
        ----------
        test_uuid : str
            Test to retrieve

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[RoutersTestsTestResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"tests/{encode_path_param(test_uuid)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    RoutersTestsTestResponse,
                    parse_obj_as(
                        type_=RoutersTestsTestResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def update(
        self,
        test_uuid: str,
        *,
        name: typing.Optional[str] = OMIT,
        type: typing.Optional[TestUpdateType] = OMIT,
        config: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        evaluators: typing.Optional[typing.Sequence[RoutersTestsEvaluatorRef]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[RoutersTestsTestResponse]:
        """
        Update a test's name, config, and/or evaluator links.

        Parameters
        ----------
        test_uuid : str
            Test to update

        name : typing.Optional[str]
            New test name. Omit to leave unchanged

        type : typing.Optional[TestUpdateType]
            Test type. Immutable — may only echo the existing value; a different value is rejected (400). Omit to leave unchanged

        config : typing.Optional[typing.Dict[str, typing.Any]]
            Replacement calibrate config. Omit to leave unchanged

        evaluators : typing.Optional[typing.Sequence[RoutersTestsEvaluatorRef]]
            Replacement evaluator links (replaces the existing set). Omit to leave links unchanged; an empty list clears them (**rejected for `conversation` tests**)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[RoutersTestsTestResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"tests/{encode_path_param(test_uuid)}",
            method="PUT",
            json={
                "name": name,
                "type": type,
                "config": config,
                "evaluators": convert_and_respect_annotation_metadata(
                    object_=evaluators,
                    annotation=typing.Optional[typing.Sequence[RoutersTestsEvaluatorRef]],
                    direction="write",
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    RoutersTestsTestResponse,
                    parse_obj_as(
                        type_=RoutersTestsTestResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
