# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..core.serialization import convert_and_respect_annotation_metadata
from ..errors.unprocessable_entity_error import UnprocessableEntityError
from ..types.http_validation_error import HttpValidationError
from ..types.trace_ingest_response import TraceIngestResponse
from ..types.trace_metadata_entry import TraceMetadataEntry
from ..types.trace_output import TraceOutput
from ..types.trace_turn import TraceTurn
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawTracesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def create(
        self,
        *,
        agent_id: str,
        input: typing.Sequence[TraceTurn],
        output: TraceOutput,
        message_id: typing.Optional[str] = OMIT,
        conversation_id: typing.Optional[str] = OMIT,
        metadata: typing.Optional[typing.Sequence[TraceMetadataEntry]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[TraceIngestResponse]:
        """
        Store a production agent turn and its conversation history for later review

        Parameters
        ----------
        agent_id : str
            ID of the agent that produced the turn. Must be an agent in your workspace

        input : typing.Sequence[TraceTurn]
            Conversation history up to the reported output, oldest turn first, in OpenAI chat format

        output : TraceOutput
            What the agent produced for this turn

        message_id : typing.Optional[str]
            Your own ID for the last user message in `input`, stored for reference only. Omit if you have none

        conversation_id : typing.Optional[str]
            Your own ID for the conversation this turn belongs to, stored for reference only. Omit if you have none

        metadata : typing.Optional[typing.Sequence[TraceMetadataEntry]]
            Key-value pairs stored with the trace. Prefer OTel `gen_ai.*` key names where they fit. Omit if you have none

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[TraceIngestResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            "traces",
            method="POST",
            json={
                "agent_id": agent_id,
                "message_id": message_id,
                "conversation_id": conversation_id,
                "input": convert_and_respect_annotation_metadata(
                    object_=input, annotation=typing.Sequence[TraceTurn], direction="write"
                ),
                "output": convert_and_respect_annotation_metadata(
                    object_=output, annotation=TraceOutput, direction="write"
                ),
                "metadata": convert_and_respect_annotation_metadata(
                    object_=metadata, annotation=typing.Optional[typing.Sequence[TraceMetadataEntry]], direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    TraceIngestResponse,
                    parse_obj_as(
                        type_=TraceIngestResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawTracesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def create(
        self,
        *,
        agent_id: str,
        input: typing.Sequence[TraceTurn],
        output: TraceOutput,
        message_id: typing.Optional[str] = OMIT,
        conversation_id: typing.Optional[str] = OMIT,
        metadata: typing.Optional[typing.Sequence[TraceMetadataEntry]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[TraceIngestResponse]:
        """
        Store a production agent turn and its conversation history for later review

        Parameters
        ----------
        agent_id : str
            ID of the agent that produced the turn. Must be an agent in your workspace

        input : typing.Sequence[TraceTurn]
            Conversation history up to the reported output, oldest turn first, in OpenAI chat format

        output : TraceOutput
            What the agent produced for this turn

        message_id : typing.Optional[str]
            Your own ID for the last user message in `input`, stored for reference only. Omit if you have none

        conversation_id : typing.Optional[str]
            Your own ID for the conversation this turn belongs to, stored for reference only. Omit if you have none

        metadata : typing.Optional[typing.Sequence[TraceMetadataEntry]]
            Key-value pairs stored with the trace. Prefer OTel `gen_ai.*` key names where they fit. Omit if you have none

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[TraceIngestResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            "traces",
            method="POST",
            json={
                "agent_id": agent_id,
                "message_id": message_id,
                "conversation_id": conversation_id,
                "input": convert_and_respect_annotation_metadata(
                    object_=input, annotation=typing.Sequence[TraceTurn], direction="write"
                ),
                "output": convert_and_respect_annotation_metadata(
                    object_=output, annotation=TraceOutput, direction="write"
                ),
                "metadata": convert_and_respect_annotation_metadata(
                    object_=metadata, annotation=typing.Optional[typing.Sequence[TraceMetadataEntry]], direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    TraceIngestResponse,
                    parse_obj_as(
                        type_=TraceIngestResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
