# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .types import (
        AgentCreateResponse,
        AgentTestRunCreateResponse,
        AgentTestRunCreateResponseStatus,
        BatchRunRequest,
        BatchTestRun,
        BatchTestRunResponse,
        BatchTestRunStatus,
        BatchTestSkip,
        BulkTestItem,
        BulkTestUploadResponse,
        ChatMessage,
        ChatMessageRole,
        ExpectedToolCall,
        HttpValidationError,
        JudgeResult,
        ResolveAgentNamesResponse,
        RoutersAgentsAgentResponse,
        RoutersAgentsAgentResponseType,
        RoutersTestsEvaluatorRef,
        RoutersTestsTestResponse,
        RoutersTestsTestResponseType,
        TaskStatus,
        TestCaseResult,
        TestCreateResponse,
        TestOutput,
        TestRunEvaluator,
        TestRunEvaluatorOutputType,
        TestRunStatusResponse,
        ToolCallOutput,
        ValidationError,
        ValidationErrorLocItem,
    )
    from .errors import UnprocessableEntityError
    from . import agent_tests, agents, tests
    from ._default_clients import DefaultAioHttpClient, DefaultAsyncHttpxClient
    from .agents import AgentCreateType
    from .client import AsyncCalibrate, Calibrate
    from .environment import CalibrateEnvironment
    from .tests import BulkTestUploadType, TestCreateType, TestUpdateType
    from .version import __version__
_dynamic_imports: typing.Dict[str, str] = {
    "AgentCreateResponse": ".types",
    "AgentCreateType": ".agents",
    "AgentTestRunCreateResponse": ".types",
    "AgentTestRunCreateResponseStatus": ".types",
    "AsyncCalibrate": ".client",
    "BatchRunRequest": ".types",
    "BatchTestRun": ".types",
    "BatchTestRunResponse": ".types",
    "BatchTestRunStatus": ".types",
    "BatchTestSkip": ".types",
    "BulkTestItem": ".types",
    "BulkTestUploadResponse": ".types",
    "BulkTestUploadType": ".tests",
    "Calibrate": ".client",
    "CalibrateEnvironment": ".environment",
    "ChatMessage": ".types",
    "ChatMessageRole": ".types",
    "DefaultAioHttpClient": "._default_clients",
    "DefaultAsyncHttpxClient": "._default_clients",
    "ExpectedToolCall": ".types",
    "HttpValidationError": ".types",
    "JudgeResult": ".types",
    "ResolveAgentNamesResponse": ".types",
    "RoutersAgentsAgentResponse": ".types",
    "RoutersAgentsAgentResponseType": ".types",
    "RoutersTestsEvaluatorRef": ".types",
    "RoutersTestsTestResponse": ".types",
    "RoutersTestsTestResponseType": ".types",
    "TaskStatus": ".types",
    "TestCaseResult": ".types",
    "TestCreateResponse": ".types",
    "TestCreateType": ".tests",
    "TestOutput": ".types",
    "TestRunEvaluator": ".types",
    "TestRunEvaluatorOutputType": ".types",
    "TestRunStatusResponse": ".types",
    "TestUpdateType": ".tests",
    "ToolCallOutput": ".types",
    "UnprocessableEntityError": ".errors",
    "ValidationError": ".types",
    "ValidationErrorLocItem": ".types",
    "__version__": ".version",
    "agent_tests": ".agent_tests",
    "agents": ".agents",
    "tests": ".tests",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "AgentCreateResponse",
    "AgentCreateType",
    "AgentTestRunCreateResponse",
    "AgentTestRunCreateResponseStatus",
    "AsyncCalibrate",
    "BatchRunRequest",
    "BatchTestRun",
    "BatchTestRunResponse",
    "BatchTestRunStatus",
    "BatchTestSkip",
    "BulkTestItem",
    "BulkTestUploadResponse",
    "BulkTestUploadType",
    "Calibrate",
    "CalibrateEnvironment",
    "ChatMessage",
    "ChatMessageRole",
    "DefaultAioHttpClient",
    "DefaultAsyncHttpxClient",
    "ExpectedToolCall",
    "HttpValidationError",
    "JudgeResult",
    "ResolveAgentNamesResponse",
    "RoutersAgentsAgentResponse",
    "RoutersAgentsAgentResponseType",
    "RoutersTestsEvaluatorRef",
    "RoutersTestsTestResponse",
    "RoutersTestsTestResponseType",
    "TaskStatus",
    "TestCaseResult",
    "TestCreateResponse",
    "TestCreateType",
    "TestOutput",
    "TestRunEvaluator",
    "TestRunEvaluatorOutputType",
    "TestRunStatusResponse",
    "TestUpdateType",
    "ToolCallOutput",
    "UnprocessableEntityError",
    "ValidationError",
    "ValidationErrorLocItem",
    "__version__",
    "agent_tests",
    "agents",
    "tests",
]
