"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .basesdk import BaseSDK
from calibrate import errors, models, utils
from calibrate._hooks import HookContext
from calibrate.types import OptionalNullable, UNSET
from calibrate.utils.unmarshal_json_response import unmarshal_json_response
from typing import Any, Iterable, List, Mapping, Optional


class Agents(BaseSDK):
    def resolve(
        self,
        *,
        names: Iterable[str],
        x_api_key: OptionalNullable[str] = UNSET,
        x_org_uuid: OptionalNullable[str] = UNSET,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.ResolveAgentNamesResponse:
        r"""Resolve Agent Names

        Resolve a list of agent names to their UUIDs within the caller's org.

        Auth accepts either a JWT (frontend) or an `sk_` API key (programmatic
        clients) via `get_org_jwt_or_api_key`, so CI tooling can map human-friendly
        agent names to the UUIDs the run/poll endpoints expect. Agent names are
        unique per org, so each name resolves to at most one agent. Names with no
        matching (non-deleted) agent in the org are returned under `not_found`.

        :param names:
        :param x_api_key:
        :param x_org_uuid:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.ResolveAgentNamesAgentsResolvePostRequest(
            x_api_key=x_api_key,
            x_org_uuid=x_org_uuid,
            body=models.ResolveAgentNamesRequest(
                names=utils.unmarshal(names, List[str]),
            ),
        )

        req = self._build_request(
            method="POST",
            path="/agents/resolve",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.body, False, False, "json", models.ResolveAgentNamesRequest
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="resolve_agent_names_agents_resolve_post",
                oauth2_scopes=None,
                security_source=self.sdk_configuration.security,
                tags=["agents"],
                extensions=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.ResolveAgentNamesResponse, http_res)
        if utils.match_response(http_res, "422", "application/json"):
            response_data = unmarshal_json_response(
                errors.HTTPValidationErrorData, http_res
            )
            raise errors.HTTPValidationError(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.CalibrateDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.CalibrateDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.CalibrateDefaultError("Unexpected response received", http_res)

    async def resolve_async(
        self,
        *,
        names: Iterable[str],
        x_api_key: OptionalNullable[str] = UNSET,
        x_org_uuid: OptionalNullable[str] = UNSET,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.ResolveAgentNamesResponse:
        r"""Resolve Agent Names

        Resolve a list of agent names to their UUIDs within the caller's org.

        Auth accepts either a JWT (frontend) or an `sk_` API key (programmatic
        clients) via `get_org_jwt_or_api_key`, so CI tooling can map human-friendly
        agent names to the UUIDs the run/poll endpoints expect. Agent names are
        unique per org, so each name resolves to at most one agent. Names with no
        matching (non-deleted) agent in the org are returned under `not_found`.

        :param names:
        :param x_api_key:
        :param x_org_uuid:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.ResolveAgentNamesAgentsResolvePostRequest(
            x_api_key=x_api_key,
            x_org_uuid=x_org_uuid,
            body=models.ResolveAgentNamesRequest(
                names=utils.unmarshal(names, List[str]),
            ),
        )

        req = self._build_request_async(
            method="POST",
            path="/agents/resolve",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.body, False, False, "json", models.ResolveAgentNamesRequest
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="resolve_agent_names_agents_resolve_post",
                oauth2_scopes=None,
                security_source=self.sdk_configuration.security,
                tags=["agents"],
                extensions=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.ResolveAgentNamesResponse, http_res)
        if utils.match_response(http_res, "422", "application/json"):
            response_data = unmarshal_json_response(
                errors.HTTPValidationErrorData, http_res
            )
            raise errors.HTTPValidationError(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.CalibrateDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.CalibrateDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.CalibrateDefaultError("Unexpected response received", http_res)

    def list(
        self,
        *,
        x_api_key: OptionalNullable[str] = UNSET,
        x_org_uuid: OptionalNullable[str] = UNSET,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> List[models.RoutersAgentToolsAgentResponse]:
        r"""List Agents

        List all agents for the caller's current org.

        Auth accepts either a JWT (frontend) or an `sk_` API key (programmatic
        clients) via `get_org_jwt_or_api_key`, so CI tooling can enumerate every
        agent UUID in the org without knowing names up front (the run/poll and
        `/resolve` endpoints accept the same key).

        :param x_api_key:
        :param x_org_uuid:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.ListAgentsAgentsGetRequest(
            x_api_key=x_api_key,
            x_org_uuid=x_org_uuid,
        )

        req = self._build_request(
            method="GET",
            path="/agents",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="list_agents_agents_get",
                oauth2_scopes=None,
                security_source=self.sdk_configuration.security,
                tags=["agents"],
                extensions=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(
                List[models.RoutersAgentToolsAgentResponse], http_res
            )
        if utils.match_response(http_res, "422", "application/json"):
            response_data = unmarshal_json_response(
                errors.HTTPValidationErrorData, http_res
            )
            raise errors.HTTPValidationError(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.CalibrateDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.CalibrateDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.CalibrateDefaultError("Unexpected response received", http_res)

    async def list_async(
        self,
        *,
        x_api_key: OptionalNullable[str] = UNSET,
        x_org_uuid: OptionalNullable[str] = UNSET,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> List[models.RoutersAgentToolsAgentResponse]:
        r"""List Agents

        List all agents for the caller's current org.

        Auth accepts either a JWT (frontend) or an `sk_` API key (programmatic
        clients) via `get_org_jwt_or_api_key`, so CI tooling can enumerate every
        agent UUID in the org without knowing names up front (the run/poll and
        `/resolve` endpoints accept the same key).

        :param x_api_key:
        :param x_org_uuid:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.ListAgentsAgentsGetRequest(
            x_api_key=x_api_key,
            x_org_uuid=x_org_uuid,
        )

        req = self._build_request_async(
            method="GET",
            path="/agents",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="list_agents_agents_get",
                oauth2_scopes=None,
                security_source=self.sdk_configuration.security,
                tags=["agents"],
                extensions=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(
                List[models.RoutersAgentToolsAgentResponse], http_res
            )
        if utils.match_response(http_res, "422", "application/json"):
            response_data = unmarshal_json_response(
                errors.HTTPValidationErrorData, http_res
            )
            raise errors.HTTPValidationError(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.CalibrateDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.CalibrateDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.CalibrateDefaultError("Unexpected response received", http_res)
