"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from typing import Any, TYPE_CHECKING

from calibrate.utils.dynamic_imports import lazy_getattr, lazy_dir

if TYPE_CHECKING:
    from .batchrunrequest import BatchRunRequest, BatchRunRequestTypedDict
    from .batchtestrun import BatchTestRun, BatchTestRunTypedDict
    from .batchtestrunresponse import (
        BatchTestRunResponse,
        BatchTestRunResponseTypedDict,
    )
    from .batchtestskip import BatchTestSkip, BatchTestSkipTypedDict
    from .get_agent_test_run_status_agent_tests_run_task_id_getop import (
        GetAgentTestRunStatusAgentTestsRunTaskIDGetRequest,
        GetAgentTestRunStatusAgentTestsRunTaskIDGetRequestTypedDict,
    )
    from .judgeresult import JudgeResult, JudgeResultTypedDict
    from .list_agents_agents_getop import (
        ListAgentsAgentsGetRequest,
        ListAgentsAgentsGetRequestTypedDict,
    )
    from .resolve_agent_names_agents_resolve_postop import (
        ResolveAgentNamesAgentsResolvePostRequest,
        ResolveAgentNamesAgentsResolvePostRequestTypedDict,
    )
    from .resolveagentnamesrequest import (
        ResolveAgentNamesRequest,
        ResolveAgentNamesRequestTypedDict,
    )
    from .resolveagentnamesresponse import (
        ResolveAgentNamesResponse,
        ResolveAgentNamesResponseTypedDict,
    )
    from .routers_agent_tools_agentresponse import (
        RoutersAgentToolsAgentResponse,
        RoutersAgentToolsAgentResponseTypedDict,
        Type,
    )
    from .run_agent_test_agent_tests_agent_agent_uuid_run_postop import (
        RunAgentTestAgentTestsAgentAgentUUIDRunPostRequest,
        RunAgentTestAgentTestsAgentAgentUUIDRunPostRequestTypedDict,
    )
    from .run_tests_batch_agent_tests_run_postop import (
        RunTestsBatchAgentTestsRunPostRequest,
        RunTestsBatchAgentTestsRunPostRequestTypedDict,
    )
    from .runtestrequest import RunTestRequest, RunTestRequestTypedDict
    from .security import Security, SecurityTypedDict
    from .taskcreateresponse import TaskCreateResponse, TaskCreateResponseTypedDict
    from .testcaseresult import TestCaseResult, TestCaseResultTypedDict
    from .testoutput import TestOutput, TestOutputTypedDict
    from .testrunstatusresponse import (
        TestRunStatusResponse,
        TestRunStatusResponseTypedDict,
    )
    from .toolcalloutput import ToolCallOutput, ToolCallOutputTypedDict
    from .validationerror import (
        Loc,
        LocTypedDict,
        ValidationError,
        ValidationErrorTypedDict,
    )

__all__ = [
    "BatchRunRequest",
    "BatchRunRequestTypedDict",
    "BatchTestRun",
    "BatchTestRunResponse",
    "BatchTestRunResponseTypedDict",
    "BatchTestRunTypedDict",
    "BatchTestSkip",
    "BatchTestSkipTypedDict",
    "GetAgentTestRunStatusAgentTestsRunTaskIDGetRequest",
    "GetAgentTestRunStatusAgentTestsRunTaskIDGetRequestTypedDict",
    "JudgeResult",
    "JudgeResultTypedDict",
    "ListAgentsAgentsGetRequest",
    "ListAgentsAgentsGetRequestTypedDict",
    "Loc",
    "LocTypedDict",
    "ResolveAgentNamesAgentsResolvePostRequest",
    "ResolveAgentNamesAgentsResolvePostRequestTypedDict",
    "ResolveAgentNamesRequest",
    "ResolveAgentNamesRequestTypedDict",
    "ResolveAgentNamesResponse",
    "ResolveAgentNamesResponseTypedDict",
    "RoutersAgentToolsAgentResponse",
    "RoutersAgentToolsAgentResponseTypedDict",
    "RunAgentTestAgentTestsAgentAgentUUIDRunPostRequest",
    "RunAgentTestAgentTestsAgentAgentUUIDRunPostRequestTypedDict",
    "RunTestRequest",
    "RunTestRequestTypedDict",
    "RunTestsBatchAgentTestsRunPostRequest",
    "RunTestsBatchAgentTestsRunPostRequestTypedDict",
    "Security",
    "SecurityTypedDict",
    "TaskCreateResponse",
    "TaskCreateResponseTypedDict",
    "TestCaseResult",
    "TestCaseResultTypedDict",
    "TestOutput",
    "TestOutputTypedDict",
    "TestRunStatusResponse",
    "TestRunStatusResponseTypedDict",
    "ToolCallOutput",
    "ToolCallOutputTypedDict",
    "Type",
    "ValidationError",
    "ValidationErrorTypedDict",
]

_dynamic_imports: dict[str, str] = {
    "BatchRunRequest": ".batchrunrequest",
    "BatchRunRequestTypedDict": ".batchrunrequest",
    "BatchTestRun": ".batchtestrun",
    "BatchTestRunTypedDict": ".batchtestrun",
    "BatchTestRunResponse": ".batchtestrunresponse",
    "BatchTestRunResponseTypedDict": ".batchtestrunresponse",
    "BatchTestSkip": ".batchtestskip",
    "BatchTestSkipTypedDict": ".batchtestskip",
    "GetAgentTestRunStatusAgentTestsRunTaskIDGetRequest": ".get_agent_test_run_status_agent_tests_run_task_id_getop",
    "GetAgentTestRunStatusAgentTestsRunTaskIDGetRequestTypedDict": ".get_agent_test_run_status_agent_tests_run_task_id_getop",
    "JudgeResult": ".judgeresult",
    "JudgeResultTypedDict": ".judgeresult",
    "ListAgentsAgentsGetRequest": ".list_agents_agents_getop",
    "ListAgentsAgentsGetRequestTypedDict": ".list_agents_agents_getop",
    "ResolveAgentNamesAgentsResolvePostRequest": ".resolve_agent_names_agents_resolve_postop",
    "ResolveAgentNamesAgentsResolvePostRequestTypedDict": ".resolve_agent_names_agents_resolve_postop",
    "ResolveAgentNamesRequest": ".resolveagentnamesrequest",
    "ResolveAgentNamesRequestTypedDict": ".resolveagentnamesrequest",
    "ResolveAgentNamesResponse": ".resolveagentnamesresponse",
    "ResolveAgentNamesResponseTypedDict": ".resolveagentnamesresponse",
    "RoutersAgentToolsAgentResponse": ".routers_agent_tools_agentresponse",
    "RoutersAgentToolsAgentResponseTypedDict": ".routers_agent_tools_agentresponse",
    "Type": ".routers_agent_tools_agentresponse",
    "RunAgentTestAgentTestsAgentAgentUUIDRunPostRequest": ".run_agent_test_agent_tests_agent_agent_uuid_run_postop",
    "RunAgentTestAgentTestsAgentAgentUUIDRunPostRequestTypedDict": ".run_agent_test_agent_tests_agent_agent_uuid_run_postop",
    "RunTestsBatchAgentTestsRunPostRequest": ".run_tests_batch_agent_tests_run_postop",
    "RunTestsBatchAgentTestsRunPostRequestTypedDict": ".run_tests_batch_agent_tests_run_postop",
    "RunTestRequest": ".runtestrequest",
    "RunTestRequestTypedDict": ".runtestrequest",
    "Security": ".security",
    "SecurityTypedDict": ".security",
    "TaskCreateResponse": ".taskcreateresponse",
    "TaskCreateResponseTypedDict": ".taskcreateresponse",
    "TestCaseResult": ".testcaseresult",
    "TestCaseResultTypedDict": ".testcaseresult",
    "TestOutput": ".testoutput",
    "TestOutputTypedDict": ".testoutput",
    "TestRunStatusResponse": ".testrunstatusresponse",
    "TestRunStatusResponseTypedDict": ".testrunstatusresponse",
    "ToolCallOutput": ".toolcalloutput",
    "ToolCallOutputTypedDict": ".toolcalloutput",
    "Loc": ".validationerror",
    "LocTypedDict": ".validationerror",
    "ValidationError": ".validationerror",
    "ValidationErrorTypedDict": ".validationerror",
}


def __getattr__(attr_name: str) -> Any:
    return lazy_getattr(
        attr_name, package=__package__, dynamic_imports=_dynamic_imports
    )


def __dir__():
    return lazy_dir(dynamic_imports=_dynamic_imports)
