"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from calibrate.types import BaseModel
from typing_extensions import TypedDict


class BatchTestSkipTypedDict(TypedDict):
    agent_name: str
    agent_uuid: str
    reason: str


class BatchTestSkip(BaseModel):
    agent_name: str

    agent_uuid: str

    reason: str
