"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from calibrate.types import BaseModel
from typing_extensions import TypedDict


class BatchTestRunTypedDict(TypedDict):
    agent_name: str
    agent_uuid: str
    task_id: str
    status: str


class BatchTestRun(BaseModel):
    agent_name: str

    agent_uuid: str

    task_id: str

    status: str
