"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from calibrate.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Any, Dict
from typing_extensions import NotRequired, TypedDict


class JudgeResultTypedDict(TypedDict):
    r"""One evaluator's verdict for a response-type test case.

    Per-row data only — anything constant across rows for the same evaluator
    (name, description, output_type, output_config, scale_min/max) lives on
    the response-level `evaluators[]` block; look it up by `evaluator_uuid`.

    `evaluator_uuid` is None for legacy runs that pre-date the evaluator-
    snapshot capture or when the evaluator can't be resolved from the
    snapshot.

    Exactly one of `match` (binary) / `score` (rating) is set per entry;
    both are None for tool-call tests, but tool-call tests don't carry
    `judge_results`.

    `variable_values` are the {{var}} substitutions used for this evaluator
    on this test case, frozen from `test_evaluators.variable_values` at
    submission time — stays on the row because it varies per test case.

    `value_name` is the human-readable label for `match`/`score` resolved
    against the rubric the run actually used (snapshot's
    `output_config.scale.name`). Falls back to `Correct`/`Wrong` for binary
    or the stringified score for rating when the snapshot lacks named
    scale entries (e.g. legacy runs captured before the rubric was
    snapshotted).
    """

    evaluator_uuid: NotRequired[Nullable[str]]
    reasoning: NotRequired[Nullable[str]]
    match: NotRequired[Nullable[bool]]
    score: NotRequired[Nullable[float]]
    value_name: NotRequired[Nullable[str]]
    variable_values: NotRequired[Nullable[Dict[str, Any]]]


class JudgeResult(BaseModel):
    r"""One evaluator's verdict for a response-type test case.

    Per-row data only — anything constant across rows for the same evaluator
    (name, description, output_type, output_config, scale_min/max) lives on
    the response-level `evaluators[]` block; look it up by `evaluator_uuid`.

    `evaluator_uuid` is None for legacy runs that pre-date the evaluator-
    snapshot capture or when the evaluator can't be resolved from the
    snapshot.

    Exactly one of `match` (binary) / `score` (rating) is set per entry;
    both are None for tool-call tests, but tool-call tests don't carry
    `judge_results`.

    `variable_values` are the {{var}} substitutions used for this evaluator
    on this test case, frozen from `test_evaluators.variable_values` at
    submission time — stays on the row because it varies per test case.

    `value_name` is the human-readable label for `match`/`score` resolved
    against the rubric the run actually used (snapshot's
    `output_config.scale.name`). Falls back to `Correct`/`Wrong` for binary
    or the stringified score for rating when the snapshot lacks named
    scale entries (e.g. legacy runs captured before the rubric was
    snapshotted).
    """

    evaluator_uuid: OptionalNullable[str] = UNSET

    reasoning: OptionalNullable[str] = UNSET

    match: OptionalNullable[bool] = UNSET

    score: OptionalNullable[float] = UNSET

    value_name: OptionalNullable[str] = UNSET

    variable_values: OptionalNullable[Dict[str, Any]] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "evaluator_uuid",
                "reasoning",
                "match",
                "score",
                "value_name",
                "variable_values",
            ]
        )
        nullable_fields = set(
            [
                "evaluator_uuid",
                "reasoning",
                "match",
                "score",
                "value_name",
                "variable_values",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
