"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from calibrate.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from calibrate.utils import FieldMetadata, HeaderMetadata
import pydantic
from pydantic import model_serializer
from typing_extensions import Annotated, NotRequired, TypedDict


class ListAgentsAgentsGetRequestTypedDict(TypedDict):
    x_api_key: NotRequired[Nullable[str]]
    x_org_uuid: NotRequired[Nullable[str]]


class ListAgentsAgentsGetRequest(BaseModel):
    x_api_key: Annotated[
        OptionalNullable[str],
        pydantic.Field(alias="X-API-Key"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ] = UNSET

    x_org_uuid: Annotated[
        OptionalNullable[str],
        pydantic.Field(alias="X-Org-UUID"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["X-API-Key", "X-Org-UUID"])
        nullable_fields = set(["X-API-Key", "X-Org-UUID"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
