"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from calibrate.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
    UnrecognizedStr,
)
from pydantic import model_serializer
from typing import Any, Dict, Literal, Union
from typing_extensions import NotRequired, TypedDict


Type = Union[
    Literal[
        "agent",
        "connection",
    ],
    UnrecognizedStr,
]


class RoutersAgentToolsAgentResponseTypedDict(TypedDict):
    uuid: str
    name: str
    type: Type
    created_at: str
    updated_at: str
    config: NotRequired[Nullable[Dict[str, Any]]]


class RoutersAgentToolsAgentResponse(BaseModel):
    uuid: str

    name: str

    type: Type

    created_at: str

    updated_at: str

    config: OptionalNullable[Dict[str, Any]] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["config"])
        nullable_fields = set(["config"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
