"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .judgeresult import JudgeResult, JudgeResultTypedDict
from .testoutput import TestOutput, TestOutputTypedDict
from calibrate.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Any, Dict, List
from typing_extensions import NotRequired, TypedDict


class TestCaseResultTypedDict(TypedDict):
    r"""Result for a single test case matching calibrate results.json structure"""

    __test__ = False  # pyright: ignore[reportGeneralTypeIssues]

    test_case_id: NotRequired[Nullable[str]]
    name: NotRequired[Nullable[str]]
    passed: NotRequired[Nullable[bool]]
    reasoning: NotRequired[Nullable[str]]
    output: NotRequired[Nullable[TestOutputTypedDict]]
    test_case: NotRequired[Nullable[Dict[str, Any]]]
    judge_results: NotRequired[Nullable[List[JudgeResultTypedDict]]]
    latency_ms: NotRequired[Nullable[float]]
    cost: NotRequired[Nullable[float]]


class TestCaseResult(BaseModel):
    r"""Result for a single test case matching calibrate results.json structure"""

    __test__ = False

    test_case_id: OptionalNullable[str] = UNSET

    name: OptionalNullable[str] = UNSET

    passed: OptionalNullable[bool] = UNSET

    reasoning: OptionalNullable[str] = UNSET

    output: OptionalNullable[TestOutput] = UNSET

    test_case: OptionalNullable[Dict[str, Any]] = UNSET

    judge_results: OptionalNullable[List[JudgeResult]] = UNSET

    latency_ms: OptionalNullable[float] = UNSET

    cost: OptionalNullable[float] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "test_case_id",
                "name",
                "passed",
                "reasoning",
                "output",
                "test_case",
                "judge_results",
                "latency_ms",
                "cost",
            ]
        )
        nullable_fields = set(
            [
                "test_case_id",
                "name",
                "passed",
                "reasoning",
                "output",
                "test_case",
                "judge_results",
                "latency_ms",
                "cost",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
