# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.evaluator_create_response import EvaluatorCreateResponse
from ..types.evaluator_detail_response_compact import EvaluatorDetailResponseCompact
from ..types.evaluator_version_create import EvaluatorVersionCreate
from ..types.output_config import OutputConfig
from ..types.paginated_response_evaluator_response import PaginatedResponseEvaluatorResponse
from ..types.variable_spec import VariableSpec
from ..types.version_create_response import VersionCreateResponse
from .raw_client import AsyncRawEvaluatorsClient, RawEvaluatorsClient
from .types.evaluator_create_data_type import EvaluatorCreateDataType
from .types.evaluator_create_evaluator_type import EvaluatorCreateEvaluatorType
from .types.evaluator_create_output_type import EvaluatorCreateOutputType
from .types.list_evaluators_request_data_type import ListEvaluatorsRequestDataType
from .types.list_evaluators_request_evaluator_type import ListEvaluatorsRequestEvaluatorType

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class EvaluatorsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawEvaluatorsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawEvaluatorsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawEvaluatorsClient
        """
        return self._raw_client

    def list(
        self,
        *,
        evaluator_type: typing.Optional[ListEvaluatorsRequestEvaluatorType] = None,
        data_type: typing.Optional[ListEvaluatorsRequestDataType] = None,
        include_defaults: typing.Optional[bool] = None,
        q: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PaginatedResponseEvaluatorResponse:
        """
        List your evaluators

        Parameters
        ----------
        evaluator_type : typing.Optional[ListEvaluatorsRequestEvaluatorType]
            Filter by what the evaluator judges. Omit for all types

        data_type : typing.Optional[ListEvaluatorsRequestDataType]
            Filter by modality. Omit for all

        include_defaults : typing.Optional[bool]
            Retained for backward compatibility and no longer filters. Your evaluators, including your editable copies of the defaults, are always returned

        q : typing.Optional[str]
            Case-insensitive substring search on `name`. Blank is a no-op

        limit : typing.Optional[int]
            Maximum number of items to return. Omit for no limit (all items)

        offset : typing.Optional[int]
            Number of items to skip before returning results

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PaginatedResponseEvaluatorResponse
            Successful Response

        Examples
        --------
        from calibrate import Calibrate

        client = Calibrate(
            api_key="YOUR_API_KEY",
        )
        client.evaluators.list()
        """
        _response = self._raw_client.list(
            evaluator_type=evaluator_type,
            data_type=data_type,
            include_defaults=include_defaults,
            q=q,
            limit=limit,
            offset=offset,
            request_options=request_options,
        )
        return _response.data

    def create(
        self,
        *,
        name: str,
        version: EvaluatorVersionCreate,
        description: typing.Optional[str] = OMIT,
        evaluator_type: typing.Optional[EvaluatorCreateEvaluatorType] = OMIT,
        data_type: typing.Optional[EvaluatorCreateDataType] = OMIT,
        output_type: typing.Optional[EvaluatorCreateOutputType] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> EvaluatorCreateResponse:
        """
        Create an evaluator along with its first version, which is set live

        Parameters
        ----------
        name : str
            Evaluator name, unique within your workspace

        version : EvaluatorVersionCreate
            The evaluator's first version. Set as live when you create the evaluator

        description : typing.Optional[str]
            Description. Omit to leave blank

        evaluator_type : typing.Optional[EvaluatorCreateEvaluatorType]
            What the evaluator judges:

            - `tts`: TTS audio
            - `stt`: one transcript
            - `llm`: a reply with its conversation history
            - `llm-general`: a standalone input and output pair
            - `conversation`: a full conversation

        data_type : typing.Optional[EvaluatorCreateDataType]
            The modality the judge reads:

            - `text`
            - `audio`

        output_type : typing.Optional[EvaluatorCreateOutputType]
            How the evaluator scores:

            - `binary`: pass or fail
            - `rating`: a numeric score, using the scale in `output_config`

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EvaluatorCreateResponse
            Successful Response

        Examples
        --------
        from calibrate import Calibrate, EvaluatorVersionCreate

        client = Calibrate(
            api_key="YOUR_API_KEY",
        )
        client.evaluators.create(
            name="name",
            version=EvaluatorVersionCreate(
                judge_model="judge_model",
                system_prompt="system_prompt",
            ),
        )
        """
        _response = self._raw_client.create(
            name=name,
            version=version,
            description=description,
            evaluator_type=evaluator_type,
            data_type=data_type,
            output_type=output_type,
            request_options=request_options,
        )
        return _response.data

    def get(
        self,
        evaluator_uuid: str,
        *,
        compact: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> EvaluatorDetailResponseCompact:
        """
        Get one evaluator with its full version history

        Parameters
        ----------
        evaluator_uuid : str
            Evaluator to retrieve

        compact : typing.Optional[bool]
            Return a compact response that omits heavy detail fields (`versions.system_prompt`, `versions.output_config`, `versions.variables`), keeping only the lightweight decision fields. Omit for full detail

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EvaluatorDetailResponseCompact
            Successful Response

        Examples
        --------
        from calibrate import Calibrate

        client = Calibrate(
            api_key="YOUR_API_KEY",
        )
        client.evaluators.get(
            evaluator_uuid="f47ac10b-58cc-4372-a567-0e02b2c3d479",
        )
        """
        _response = self._raw_client.get(evaluator_uuid, compact=compact, request_options=request_options)
        return _response.data

    def create_version(
        self,
        evaluator_uuid: str,
        *,
        judge_model: str,
        system_prompt: str,
        output_config: typing.Optional[OutputConfig] = OMIT,
        variables: typing.Optional[typing.Sequence[VariableSpec]] = OMIT,
        make_live: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> VersionCreateResponse:
        """
        Add a new version to an evaluator you created

        Parameters
        ----------
        evaluator_uuid : str
            Evaluator to add a version to

        judge_model : str
            The model that runs the judge, named the way its provider does, for example `openai/gpt-4.1` or `anthropic/claude-sonnet-4`

        system_prompt : str
            Judge system prompt. May contain `{{variable}}` placeholders

        output_config : typing.Optional[OutputConfig]
            The scale points and their labels. Required for a `rating` evaluator. A `binary` evaluator uses the default Correct/Wrong labels unless you set your own

        variables : typing.Optional[typing.Sequence[VariableSpec]]
            Declared prompt variables. Omit if the prompt has none. After the first version the variable names are fixed. You can change a variable's description or default, but not add, remove, or rename one

        make_live : typing.Optional[bool]
            When `true`, immediately point the evaluator's live version at this new version

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        VersionCreateResponse
            Successful Response

        Examples
        --------
        from calibrate import Calibrate

        client = Calibrate(
            api_key="YOUR_API_KEY",
        )
        client.evaluators.create_version(
            evaluator_uuid="f47ac10b-58cc-4372-a567-0e02b2c3d479",
            judge_model="judge_model",
            system_prompt="system_prompt",
        )
        """
        _response = self._raw_client.create_version(
            evaluator_uuid,
            judge_model=judge_model,
            system_prompt=system_prompt,
            output_config=output_config,
            variables=variables,
            make_live=make_live,
            request_options=request_options,
        )
        return _response.data


class AsyncEvaluatorsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawEvaluatorsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawEvaluatorsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawEvaluatorsClient
        """
        return self._raw_client

    async def list(
        self,
        *,
        evaluator_type: typing.Optional[ListEvaluatorsRequestEvaluatorType] = None,
        data_type: typing.Optional[ListEvaluatorsRequestDataType] = None,
        include_defaults: typing.Optional[bool] = None,
        q: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PaginatedResponseEvaluatorResponse:
        """
        List your evaluators

        Parameters
        ----------
        evaluator_type : typing.Optional[ListEvaluatorsRequestEvaluatorType]
            Filter by what the evaluator judges. Omit for all types

        data_type : typing.Optional[ListEvaluatorsRequestDataType]
            Filter by modality. Omit for all

        include_defaults : typing.Optional[bool]
            Retained for backward compatibility and no longer filters. Your evaluators, including your editable copies of the defaults, are always returned

        q : typing.Optional[str]
            Case-insensitive substring search on `name`. Blank is a no-op

        limit : typing.Optional[int]
            Maximum number of items to return. Omit for no limit (all items)

        offset : typing.Optional[int]
            Number of items to skip before returning results

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PaginatedResponseEvaluatorResponse
            Successful Response

        Examples
        --------
        import asyncio

        from calibrate import AsyncCalibrate

        client = AsyncCalibrate(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.evaluators.list()


        asyncio.run(main())
        """
        _response = await self._raw_client.list(
            evaluator_type=evaluator_type,
            data_type=data_type,
            include_defaults=include_defaults,
            q=q,
            limit=limit,
            offset=offset,
            request_options=request_options,
        )
        return _response.data

    async def create(
        self,
        *,
        name: str,
        version: EvaluatorVersionCreate,
        description: typing.Optional[str] = OMIT,
        evaluator_type: typing.Optional[EvaluatorCreateEvaluatorType] = OMIT,
        data_type: typing.Optional[EvaluatorCreateDataType] = OMIT,
        output_type: typing.Optional[EvaluatorCreateOutputType] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> EvaluatorCreateResponse:
        """
        Create an evaluator along with its first version, which is set live

        Parameters
        ----------
        name : str
            Evaluator name, unique within your workspace

        version : EvaluatorVersionCreate
            The evaluator's first version. Set as live when you create the evaluator

        description : typing.Optional[str]
            Description. Omit to leave blank

        evaluator_type : typing.Optional[EvaluatorCreateEvaluatorType]
            What the evaluator judges:

            - `tts`: TTS audio
            - `stt`: one transcript
            - `llm`: a reply with its conversation history
            - `llm-general`: a standalone input and output pair
            - `conversation`: a full conversation

        data_type : typing.Optional[EvaluatorCreateDataType]
            The modality the judge reads:

            - `text`
            - `audio`

        output_type : typing.Optional[EvaluatorCreateOutputType]
            How the evaluator scores:

            - `binary`: pass or fail
            - `rating`: a numeric score, using the scale in `output_config`

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EvaluatorCreateResponse
            Successful Response

        Examples
        --------
        import asyncio

        from calibrate import AsyncCalibrate, EvaluatorVersionCreate

        client = AsyncCalibrate(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.evaluators.create(
                name="name",
                version=EvaluatorVersionCreate(
                    judge_model="judge_model",
                    system_prompt="system_prompt",
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(
            name=name,
            version=version,
            description=description,
            evaluator_type=evaluator_type,
            data_type=data_type,
            output_type=output_type,
            request_options=request_options,
        )
        return _response.data

    async def get(
        self,
        evaluator_uuid: str,
        *,
        compact: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> EvaluatorDetailResponseCompact:
        """
        Get one evaluator with its full version history

        Parameters
        ----------
        evaluator_uuid : str
            Evaluator to retrieve

        compact : typing.Optional[bool]
            Return a compact response that omits heavy detail fields (`versions.system_prompt`, `versions.output_config`, `versions.variables`), keeping only the lightweight decision fields. Omit for full detail

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EvaluatorDetailResponseCompact
            Successful Response

        Examples
        --------
        import asyncio

        from calibrate import AsyncCalibrate

        client = AsyncCalibrate(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.evaluators.get(
                evaluator_uuid="f47ac10b-58cc-4372-a567-0e02b2c3d479",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(evaluator_uuid, compact=compact, request_options=request_options)
        return _response.data

    async def create_version(
        self,
        evaluator_uuid: str,
        *,
        judge_model: str,
        system_prompt: str,
        output_config: typing.Optional[OutputConfig] = OMIT,
        variables: typing.Optional[typing.Sequence[VariableSpec]] = OMIT,
        make_live: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> VersionCreateResponse:
        """
        Add a new version to an evaluator you created

        Parameters
        ----------
        evaluator_uuid : str
            Evaluator to add a version to

        judge_model : str
            The model that runs the judge, named the way its provider does, for example `openai/gpt-4.1` or `anthropic/claude-sonnet-4`

        system_prompt : str
            Judge system prompt. May contain `{{variable}}` placeholders

        output_config : typing.Optional[OutputConfig]
            The scale points and their labels. Required for a `rating` evaluator. A `binary` evaluator uses the default Correct/Wrong labels unless you set your own

        variables : typing.Optional[typing.Sequence[VariableSpec]]
            Declared prompt variables. Omit if the prompt has none. After the first version the variable names are fixed. You can change a variable's description or default, but not add, remove, or rename one

        make_live : typing.Optional[bool]
            When `true`, immediately point the evaluator's live version at this new version

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        VersionCreateResponse
            Successful Response

        Examples
        --------
        import asyncio

        from calibrate import AsyncCalibrate

        client = AsyncCalibrate(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.evaluators.create_version(
                evaluator_uuid="f47ac10b-58cc-4372-a567-0e02b2c3d479",
                judge_model="judge_model",
                system_prompt="system_prompt",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_version(
            evaluator_uuid,
            judge_model=judge_model,
            system_prompt=system_prompt,
            output_config=output_config,
            variables=variables,
            make_live=make_live,
            request_options=request_options,
        )
        return _response.data
