# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import encode_path_param
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..core.serialization import convert_and_respect_annotation_metadata
from ..errors.unprocessable_entity_error import UnprocessableEntityError
from ..types.evaluator_create_response import EvaluatorCreateResponse
from ..types.evaluator_detail_response_compact import EvaluatorDetailResponseCompact
from ..types.evaluator_version_create import EvaluatorVersionCreate
from ..types.http_validation_error import HttpValidationError
from ..types.output_config import OutputConfig
from ..types.paginated_response_evaluator_response import PaginatedResponseEvaluatorResponse
from ..types.variable_spec import VariableSpec
from ..types.version_create_response import VersionCreateResponse
from .types.evaluator_create_data_type import EvaluatorCreateDataType
from .types.evaluator_create_evaluator_type import EvaluatorCreateEvaluatorType
from .types.evaluator_create_output_type import EvaluatorCreateOutputType
from .types.list_evaluators_request_data_type import ListEvaluatorsRequestDataType
from .types.list_evaluators_request_evaluator_type import ListEvaluatorsRequestEvaluatorType
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawEvaluatorsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list(
        self,
        *,
        evaluator_type: typing.Optional[ListEvaluatorsRequestEvaluatorType] = None,
        data_type: typing.Optional[ListEvaluatorsRequestDataType] = None,
        include_defaults: typing.Optional[bool] = None,
        q: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[PaginatedResponseEvaluatorResponse]:
        """
        List your evaluators

        Parameters
        ----------
        evaluator_type : typing.Optional[ListEvaluatorsRequestEvaluatorType]
            Filter by what the evaluator judges. Omit for all types

        data_type : typing.Optional[ListEvaluatorsRequestDataType]
            Filter by modality. Omit for all

        include_defaults : typing.Optional[bool]
            Retained for backward compatibility and no longer filters. Your evaluators, including your editable copies of the defaults, are always returned

        q : typing.Optional[str]
            Case-insensitive substring search on `name`. Blank is a no-op

        limit : typing.Optional[int]
            Maximum number of items to return. Omit for no limit (all items)

        offset : typing.Optional[int]
            Number of items to skip before returning results

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[PaginatedResponseEvaluatorResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            "evaluators",
            method="GET",
            params={
                "evaluator_type": evaluator_type,
                "data_type": data_type,
                "include_defaults": include_defaults,
                "q": q,
                "limit": limit,
                "offset": offset,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PaginatedResponseEvaluatorResponse,
                    parse_obj_as(
                        type_=PaginatedResponseEvaluatorResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def create(
        self,
        *,
        name: str,
        version: EvaluatorVersionCreate,
        description: typing.Optional[str] = OMIT,
        evaluator_type: typing.Optional[EvaluatorCreateEvaluatorType] = OMIT,
        data_type: typing.Optional[EvaluatorCreateDataType] = OMIT,
        output_type: typing.Optional[EvaluatorCreateOutputType] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[EvaluatorCreateResponse]:
        """
        Create an evaluator along with its first version, which is set live

        Parameters
        ----------
        name : str
            Evaluator name, unique within your workspace

        version : EvaluatorVersionCreate
            The evaluator's first version. Set as live when you create the evaluator

        description : typing.Optional[str]
            Description. Omit to leave blank

        evaluator_type : typing.Optional[EvaluatorCreateEvaluatorType]
            What the evaluator judges:

            - `tts`: TTS audio
            - `stt`: one transcript
            - `llm`: a reply with its conversation history
            - `llm-general`: a standalone input and output pair
            - `conversation`: a full conversation

        data_type : typing.Optional[EvaluatorCreateDataType]
            The modality the judge reads:

            - `text`
            - `audio`

        output_type : typing.Optional[EvaluatorCreateOutputType]
            How the evaluator scores:

            - `binary`: pass or fail
            - `rating`: a numeric score, using the scale in `output_config`

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[EvaluatorCreateResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            "evaluators",
            method="POST",
            json={
                "name": name,
                "description": description,
                "evaluator_type": evaluator_type,
                "data_type": data_type,
                "output_type": output_type,
                "version": convert_and_respect_annotation_metadata(
                    object_=version, annotation=EvaluatorVersionCreate, direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    EvaluatorCreateResponse,
                    parse_obj_as(
                        type_=EvaluatorCreateResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get(
        self,
        evaluator_uuid: str,
        *,
        compact: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[EvaluatorDetailResponseCompact]:
        """
        Get one evaluator with its full version history

        Parameters
        ----------
        evaluator_uuid : str
            Evaluator to retrieve

        compact : typing.Optional[bool]
            Return a compact response that omits heavy detail fields (`versions.system_prompt`, `versions.output_config`, `versions.variables`), keeping only the lightweight decision fields. Omit for full detail

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[EvaluatorDetailResponseCompact]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"evaluators/{encode_path_param(evaluator_uuid)}",
            method="GET",
            params={
                "compact": compact,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    EvaluatorDetailResponseCompact,
                    parse_obj_as(
                        type_=EvaluatorDetailResponseCompact,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def create_version(
        self,
        evaluator_uuid: str,
        *,
        judge_model: str,
        system_prompt: str,
        output_config: typing.Optional[OutputConfig] = OMIT,
        variables: typing.Optional[typing.Sequence[VariableSpec]] = OMIT,
        make_live: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[VersionCreateResponse]:
        """
        Add a new version to an evaluator you created

        Parameters
        ----------
        evaluator_uuid : str
            Evaluator to add a version to

        judge_model : str
            The model that runs the judge, named the way its provider does, for example `openai/gpt-4.1` or `anthropic/claude-sonnet-4`

        system_prompt : str
            Judge system prompt. May contain `{{variable}}` placeholders

        output_config : typing.Optional[OutputConfig]
            The scale points and their labels. Required for a `rating` evaluator. A `binary` evaluator uses the default Correct/Wrong labels unless you set your own

        variables : typing.Optional[typing.Sequence[VariableSpec]]
            Declared prompt variables. Omit if the prompt has none. After the first version the variable names are fixed. You can change a variable's description or default, but not add, remove, or rename one

        make_live : typing.Optional[bool]
            When `true`, immediately point the evaluator's live version at this new version

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[VersionCreateResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"evaluators/{encode_path_param(evaluator_uuid)}/versions",
            method="POST",
            json={
                "judge_model": judge_model,
                "system_prompt": system_prompt,
                "output_config": convert_and_respect_annotation_metadata(
                    object_=output_config, annotation=typing.Optional[OutputConfig], direction="write"
                ),
                "variables": convert_and_respect_annotation_metadata(
                    object_=variables, annotation=typing.Optional[typing.Sequence[VariableSpec]], direction="write"
                ),
                "make_live": make_live,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    VersionCreateResponse,
                    parse_obj_as(
                        type_=VersionCreateResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawEvaluatorsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list(
        self,
        *,
        evaluator_type: typing.Optional[ListEvaluatorsRequestEvaluatorType] = None,
        data_type: typing.Optional[ListEvaluatorsRequestDataType] = None,
        include_defaults: typing.Optional[bool] = None,
        q: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[PaginatedResponseEvaluatorResponse]:
        """
        List your evaluators

        Parameters
        ----------
        evaluator_type : typing.Optional[ListEvaluatorsRequestEvaluatorType]
            Filter by what the evaluator judges. Omit for all types

        data_type : typing.Optional[ListEvaluatorsRequestDataType]
            Filter by modality. Omit for all

        include_defaults : typing.Optional[bool]
            Retained for backward compatibility and no longer filters. Your evaluators, including your editable copies of the defaults, are always returned

        q : typing.Optional[str]
            Case-insensitive substring search on `name`. Blank is a no-op

        limit : typing.Optional[int]
            Maximum number of items to return. Omit for no limit (all items)

        offset : typing.Optional[int]
            Number of items to skip before returning results

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[PaginatedResponseEvaluatorResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            "evaluators",
            method="GET",
            params={
                "evaluator_type": evaluator_type,
                "data_type": data_type,
                "include_defaults": include_defaults,
                "q": q,
                "limit": limit,
                "offset": offset,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PaginatedResponseEvaluatorResponse,
                    parse_obj_as(
                        type_=PaginatedResponseEvaluatorResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def create(
        self,
        *,
        name: str,
        version: EvaluatorVersionCreate,
        description: typing.Optional[str] = OMIT,
        evaluator_type: typing.Optional[EvaluatorCreateEvaluatorType] = OMIT,
        data_type: typing.Optional[EvaluatorCreateDataType] = OMIT,
        output_type: typing.Optional[EvaluatorCreateOutputType] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[EvaluatorCreateResponse]:
        """
        Create an evaluator along with its first version, which is set live

        Parameters
        ----------
        name : str
            Evaluator name, unique within your workspace

        version : EvaluatorVersionCreate
            The evaluator's first version. Set as live when you create the evaluator

        description : typing.Optional[str]
            Description. Omit to leave blank

        evaluator_type : typing.Optional[EvaluatorCreateEvaluatorType]
            What the evaluator judges:

            - `tts`: TTS audio
            - `stt`: one transcript
            - `llm`: a reply with its conversation history
            - `llm-general`: a standalone input and output pair
            - `conversation`: a full conversation

        data_type : typing.Optional[EvaluatorCreateDataType]
            The modality the judge reads:

            - `text`
            - `audio`

        output_type : typing.Optional[EvaluatorCreateOutputType]
            How the evaluator scores:

            - `binary`: pass or fail
            - `rating`: a numeric score, using the scale in `output_config`

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[EvaluatorCreateResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            "evaluators",
            method="POST",
            json={
                "name": name,
                "description": description,
                "evaluator_type": evaluator_type,
                "data_type": data_type,
                "output_type": output_type,
                "version": convert_and_respect_annotation_metadata(
                    object_=version, annotation=EvaluatorVersionCreate, direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    EvaluatorCreateResponse,
                    parse_obj_as(
                        type_=EvaluatorCreateResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get(
        self,
        evaluator_uuid: str,
        *,
        compact: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[EvaluatorDetailResponseCompact]:
        """
        Get one evaluator with its full version history

        Parameters
        ----------
        evaluator_uuid : str
            Evaluator to retrieve

        compact : typing.Optional[bool]
            Return a compact response that omits heavy detail fields (`versions.system_prompt`, `versions.output_config`, `versions.variables`), keeping only the lightweight decision fields. Omit for full detail

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[EvaluatorDetailResponseCompact]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"evaluators/{encode_path_param(evaluator_uuid)}",
            method="GET",
            params={
                "compact": compact,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    EvaluatorDetailResponseCompact,
                    parse_obj_as(
                        type_=EvaluatorDetailResponseCompact,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def create_version(
        self,
        evaluator_uuid: str,
        *,
        judge_model: str,
        system_prompt: str,
        output_config: typing.Optional[OutputConfig] = OMIT,
        variables: typing.Optional[typing.Sequence[VariableSpec]] = OMIT,
        make_live: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[VersionCreateResponse]:
        """
        Add a new version to an evaluator you created

        Parameters
        ----------
        evaluator_uuid : str
            Evaluator to add a version to

        judge_model : str
            The model that runs the judge, named the way its provider does, for example `openai/gpt-4.1` or `anthropic/claude-sonnet-4`

        system_prompt : str
            Judge system prompt. May contain `{{variable}}` placeholders

        output_config : typing.Optional[OutputConfig]
            The scale points and their labels. Required for a `rating` evaluator. A `binary` evaluator uses the default Correct/Wrong labels unless you set your own

        variables : typing.Optional[typing.Sequence[VariableSpec]]
            Declared prompt variables. Omit if the prompt has none. After the first version the variable names are fixed. You can change a variable's description or default, but not add, remove, or rename one

        make_live : typing.Optional[bool]
            When `true`, immediately point the evaluator's live version at this new version

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[VersionCreateResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"evaluators/{encode_path_param(evaluator_uuid)}/versions",
            method="POST",
            json={
                "judge_model": judge_model,
                "system_prompt": system_prompt,
                "output_config": convert_and_respect_annotation_metadata(
                    object_=output_config, annotation=typing.Optional[OutputConfig], direction="write"
                ),
                "variables": convert_and_respect_annotation_metadata(
                    object_=variables, annotation=typing.Optional[typing.Sequence[VariableSpec]], direction="write"
                ),
                "make_live": make_live,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    VersionCreateResponse,
                    parse_obj_as(
                        type_=VersionCreateResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
