# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.agent_test_run_create_response import AgentTestRunCreateResponse
from ..types.agent_tests_bulk_unlink_response import AgentTestsBulkUnlinkResponse
from ..types.agent_tests_create_response import AgentTestsCreateResponse
from ..types.batch_run_request import BatchRunRequest
from ..types.batch_test_run_response import BatchTestRunResponse
from ..types.benchmark_status_response import BenchmarkStatusResponse
from ..types.paginated_response_agent_test_run_list_item import PaginatedResponseAgentTestRunListItem
from ..types.paginated_response_test_list_response import PaginatedResponseTestListResponse
from ..types.task_status import TaskStatus
from ..types.test_case_result import TestCaseResult
from ..types.test_run_status_response import TestRunStatusResponse
from .raw_client import AsyncRawAgentTestsClient, RawAgentTestsClient
from .types.get_benchmark_agent_tests_request_mode import GetBenchmarkAgentTestsRequestMode
from .types.get_run_agent_tests_request_mode import GetRunAgentTestsRequestMode
from .types.list_for_agent_agent_tests_request_q_mode import ListForAgentAgentTestsRequestQMode
from .types.list_runs_for_agent_agent_tests_request_type import ListRunsForAgentAgentTestsRequestType

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class AgentTestsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawAgentTestsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawAgentTestsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawAgentTestsClient
        """
        return self._raw_client

    def link(
        self,
        *,
        agent_uuid: str,
        test_uuids: typing.Sequence[str],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AgentTestsCreateResponse:
        """
        Link one or more tests to an agent. Tests that are already linked are skipped.

        Parameters
        ----------
        agent_uuid : str
            Agent to link tests to

        test_uuids : typing.Sequence[str]
            Tests to link. Any that are already linked are skipped

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AgentTestsCreateResponse
            Successful Response

        Examples
        --------
        from calibrate import Calibrate

        client = Calibrate(
            api_key="YOUR_API_KEY",
        )
        client.agent_tests.link(
            agent_uuid="f47ac10b-58cc-4372-a567-0e02b2c3d479",
            test_uuids=["b1c2d3e4-f5a6-7890-bcde-f12345678901"],
        )
        """
        _response = self._raw_client.link(agent_uuid=agent_uuid, test_uuids=test_uuids, request_options=request_options)
        return _response.data

    def list_for_agent(
        self,
        agent_uuid: str,
        *,
        type: typing.Optional[typing.Sequence[str]] = None,
        q: typing.Optional[str] = None,
        q_mode: typing.Optional[ListForAgentAgentTestsRequestQMode] = None,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PaginatedResponseTestListResponse:
        """
        List the tests linked to an agent.

        Parameters
        ----------
        agent_uuid : str
            Agent whose linked tests to list

        type : typing.Optional[typing.Sequence[str]]
            Keep only tests of these types. Repeat the parameter or pass one comma-separated value. Accepts `response`, `tool_call`, `conversation`, `general`

        q : typing.Optional[str]
            Case-insensitive search on `name`. Blank is a no-op

        q_mode : typing.Optional[ListForAgentAgentTestsRequestQMode]
            How to match `q` against the searched fields

        limit : typing.Optional[int]
            Maximum number of items to return. Omit for no limit (all items)

        offset : typing.Optional[int]
            Number of items to skip before returning results

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PaginatedResponseTestListResponse
            Successful Response

        Examples
        --------
        from calibrate import Calibrate

        client = Calibrate(
            api_key="YOUR_API_KEY",
        )
        client.agent_tests.list_for_agent(
            agent_uuid="f47ac10b-58cc-4372-a567-0e02b2c3d479",
        )
        """
        _response = self._raw_client.list_for_agent(
            agent_uuid, type=type, q=q, q_mode=q_mode, limit=limit, offset=offset, request_options=request_options
        )
        return _response.data

    def list_runs_for_agent(
        self,
        agent_uuid: str,
        *,
        type: typing.Optional[ListRunsForAgentAgentTestsRequestType] = None,
        status: typing.Optional[TaskStatus] = None,
        has_failures: typing.Optional[bool] = None,
        around: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PaginatedResponseAgentTestRunListItem:
        """
        List an agent's test runs with their results

        Parameters
        ----------
        agent_uuid : str
            Agent whose test runs to list

        type : typing.Optional[ListRunsForAgentAgentTestsRequestType]
            Filter by run type. Omit to return both:
            - `llm-unit-test`: single runs of an agent's tests
            - `llm-benchmark`: multi-model comparisons

        status : typing.Optional[TaskStatus]
            Filter by run status. Omit for all statuses

        has_failures : typing.Optional[bool]
            Filter by whether the run has any failing test case or model. `true` returns only runs with failures (or errors), `false` only clean runs. Omit for both

        around : typing.Optional[str]
            ID of a run to jump to, returning the page that contains it instead of the page at `offset`

        limit : typing.Optional[int]
            Maximum number of items to return. Omit for no limit (all items)

        offset : typing.Optional[int]
            Number of items to skip before returning results

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PaginatedResponseAgentTestRunListItem
            Successful Response

        Examples
        --------
        from calibrate import Calibrate

        client = Calibrate(
            api_key="YOUR_API_KEY",
        )
        client.agent_tests.list_runs_for_agent(
            agent_uuid="f47ac10b-58cc-4372-a567-0e02b2c3d479",
        )
        """
        _response = self._raw_client.list_runs_for_agent(
            agent_uuid,
            type=type,
            status=status,
            has_failures=has_failures,
            around=around,
            limit=limit,
            offset=offset,
            request_options=request_options,
        )
        return _response.data

    def bulk_unlink(
        self,
        *,
        agent_uuid: str,
        test_uuids: typing.Sequence[str],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AgentTestsBulkUnlinkResponse:
        """
        Unlink one or more tests from an agent. Tests that are not linked are skipped.

        Parameters
        ----------
        agent_uuid : str
            Agent to unlink tests from

        test_uuids : typing.Sequence[str]
            Tests to unlink from the agent

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AgentTestsBulkUnlinkResponse
            Successful Response

        Examples
        --------
        from calibrate import Calibrate

        client = Calibrate(
            api_key="YOUR_API_KEY",
        )
        client.agent_tests.bulk_unlink(
            agent_uuid="f47ac10b-58cc-4372-a567-0e02b2c3d479",
            test_uuids=["b1c2d3e4-f5a6-7890-bcde-f12345678901"],
        )
        """
        _response = self._raw_client.bulk_unlink(
            agent_uuid=agent_uuid, test_uuids=test_uuids, request_options=request_options
        )
        return _response.data

    def run(
        self,
        agent_uuid: str,
        *,
        test_uuids: typing.Optional[typing.Sequence[str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AgentTestRunCreateResponse:
        """
        Run an agent's linked tests as a background job, returning a task ID to poll.

        Parameters
        ----------
        agent_uuid : str
            Agent to test

        test_uuids : typing.Optional[typing.Sequence[str]]
            Tests to run. Omit to run all tests linked to the agent

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AgentTestRunCreateResponse
            Successful Response

        Examples
        --------
        from calibrate import Calibrate

        client = Calibrate(
            api_key="YOUR_API_KEY",
        )
        client.agent_tests.run(
            agent_uuid="f47ac10b-58cc-4372-a567-0e02b2c3d479",
        )
        """
        _response = self._raw_client.run(agent_uuid, test_uuids=test_uuids, request_options=request_options)
        return _response.data

    def run_batch(
        self,
        *,
        request: typing.Optional[BatchRunRequest] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> BatchTestRunResponse:
        """
        Run agent tests for every agent, or for a selected set.

        Parameters
        ----------
        request : typing.Optional[BatchRunRequest]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BatchTestRunResponse
            Successful Response

        Examples
        --------
        from calibrate import BatchRunRequest, Calibrate

        client = Calibrate(
            api_key="YOUR_API_KEY",
        )
        client.agent_tests.run_batch(
            request=BatchRunRequest(),
        )
        """
        _response = self._raw_client.run_batch(request=request, request_options=request_options)
        return _response.data

    def get_run(
        self,
        task_id: str,
        *,
        only_failed: typing.Optional[bool] = None,
        mode: typing.Optional[GetRunAgentTestsRequestMode] = None,
        compact: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> TestRunStatusResponse:
        """
        Poll a test run for its status and evaluation results.

        Parameters
        ----------
        task_id : str
            Test run to poll for status and results

        only_failed : typing.Optional[bool]
            Return only failing test cases. Omit to return every case

        mode : typing.Optional[GetRunAgentTestsRequestMode]
            How much of each test case to return. `full` returns every field of every case. `summary` returns one light row per case, with its ID, name, verdict and short reason, leaving out the conversation, the agent's output and the evaluator verdicts. Read those one case at a time from `GET /agent-tests/run/{task_id}/results/{test_uuid}`

        compact : typing.Optional[bool]
            Return a compact response that omits heavy detail fields (`results.output`, `results.test_case`, `results.judge_results`, `results.reasoning`, `evaluators.output_config`), keeping only the lightweight decision fields. Omit for full detail

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TestRunStatusResponse
            Successful Response

        Examples
        --------
        from calibrate import Calibrate

        client = Calibrate(
            api_key="YOUR_API_KEY",
        )
        client.agent_tests.get_run(
            task_id="a3b2c1d0-e5f4-3210-abcd-ef1234567890",
        )
        """
        _response = self._raw_client.get_run(
            task_id, only_failed=only_failed, mode=mode, compact=compact, request_options=request_options
        )
        return _response.data

    def get_run_case(
        self,
        task_id: str,
        test_uuid: str,
        *,
        model: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> TestCaseResult:
        """
        Get the full result of one test case in a run

        Parameters
        ----------
        task_id : str
            Test run or benchmark the case was run in

        test_uuid : str
            The test whose result to read, as `test_uuid` on the case

        model : typing.Optional[str]
            Which model's answer to read. Required for a benchmark, which runs every test once per model

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TestCaseResult
            Successful Response

        Examples
        --------
        from calibrate import Calibrate

        client = Calibrate(
            api_key="YOUR_API_KEY",
        )
        client.agent_tests.get_run_case(
            task_id="a3b2c1d0-e5f4-3210-abcd-ef1234567890",
            test_uuid="b1c2d3e4-f5a6-7890-bcde-f12345678901",
        )
        """
        _response = self._raw_client.get_run_case(task_id, test_uuid, model=model, request_options=request_options)
        return _response.data

    def benchmark(
        self,
        agent_uuid: str,
        *,
        models: typing.Sequence[str],
        test_uuids: typing.Optional[typing.Sequence[str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AgentTestRunCreateResponse:
        """
        Run a multi-model benchmark on an agent's linked tests as a background job.

        Parameters
        ----------
        agent_uuid : str
            Agent to benchmark

        models : typing.Sequence[str]
            Model names to benchmark

        test_uuids : typing.Optional[typing.Sequence[str]]
            A subset of the agent's linked tests to benchmark. Each ID must be linked to the agent. Omit to run all linked tests

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AgentTestRunCreateResponse
            Successful Response

        Examples
        --------
        from calibrate import Calibrate

        client = Calibrate(
            api_key="YOUR_API_KEY",
        )
        client.agent_tests.benchmark(
            agent_uuid="f47ac10b-58cc-4372-a567-0e02b2c3d479",
            models=["openai/gpt-4.1", "anthropic/claude-sonnet-4"],
        )
        """
        _response = self._raw_client.benchmark(
            agent_uuid, models=models, test_uuids=test_uuids, request_options=request_options
        )
        return _response.data

    def get_benchmark(
        self,
        task_id: str,
        *,
        only_failed: typing.Optional[bool] = None,
        mode: typing.Optional[GetBenchmarkAgentTestsRequestMode] = None,
        compact: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> BenchmarkStatusResponse:
        """
        Get the results of a benchmark run

        Parameters
        ----------
        task_id : str
            Benchmark run to poll for status and results

        only_failed : typing.Optional[bool]
            Return only failing test cases for each model. Omit to return every case

        mode : typing.Optional[GetBenchmarkAgentTestsRequestMode]
            How much of each test case to return. `full` returns every field of every case. `summary` returns one light row per case, with its ID, name, verdict and short reason, leaving out the conversation, the agent's output and the evaluator verdicts. Read those one case at a time from `GET /agent-tests/run/{task_id}/results/{test_uuid}`

        compact : typing.Optional[bool]
            Return a compact response that omits heavy detail fields (`model_results.test_results`, `evaluators.output_config`), keeping only the lightweight decision fields. Omit for full detail

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BenchmarkStatusResponse
            Successful Response

        Examples
        --------
        from calibrate import Calibrate

        client = Calibrate(
            api_key="YOUR_API_KEY",
        )
        client.agent_tests.get_benchmark(
            task_id="a3b2c1d0-e5f4-3210-abcd-ef1234567890",
        )
        """
        _response = self._raw_client.get_benchmark(
            task_id, only_failed=only_failed, mode=mode, compact=compact, request_options=request_options
        )
        return _response.data


class AsyncAgentTestsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawAgentTestsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawAgentTestsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawAgentTestsClient
        """
        return self._raw_client

    async def link(
        self,
        *,
        agent_uuid: str,
        test_uuids: typing.Sequence[str],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AgentTestsCreateResponse:
        """
        Link one or more tests to an agent. Tests that are already linked are skipped.

        Parameters
        ----------
        agent_uuid : str
            Agent to link tests to

        test_uuids : typing.Sequence[str]
            Tests to link. Any that are already linked are skipped

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AgentTestsCreateResponse
            Successful Response

        Examples
        --------
        import asyncio

        from calibrate import AsyncCalibrate

        client = AsyncCalibrate(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.agent_tests.link(
                agent_uuid="f47ac10b-58cc-4372-a567-0e02b2c3d479",
                test_uuids=["b1c2d3e4-f5a6-7890-bcde-f12345678901"],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.link(
            agent_uuid=agent_uuid, test_uuids=test_uuids, request_options=request_options
        )
        return _response.data

    async def list_for_agent(
        self,
        agent_uuid: str,
        *,
        type: typing.Optional[typing.Sequence[str]] = None,
        q: typing.Optional[str] = None,
        q_mode: typing.Optional[ListForAgentAgentTestsRequestQMode] = None,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PaginatedResponseTestListResponse:
        """
        List the tests linked to an agent.

        Parameters
        ----------
        agent_uuid : str
            Agent whose linked tests to list

        type : typing.Optional[typing.Sequence[str]]
            Keep only tests of these types. Repeat the parameter or pass one comma-separated value. Accepts `response`, `tool_call`, `conversation`, `general`

        q : typing.Optional[str]
            Case-insensitive search on `name`. Blank is a no-op

        q_mode : typing.Optional[ListForAgentAgentTestsRequestQMode]
            How to match `q` against the searched fields

        limit : typing.Optional[int]
            Maximum number of items to return. Omit for no limit (all items)

        offset : typing.Optional[int]
            Number of items to skip before returning results

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PaginatedResponseTestListResponse
            Successful Response

        Examples
        --------
        import asyncio

        from calibrate import AsyncCalibrate

        client = AsyncCalibrate(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.agent_tests.list_for_agent(
                agent_uuid="f47ac10b-58cc-4372-a567-0e02b2c3d479",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_for_agent(
            agent_uuid, type=type, q=q, q_mode=q_mode, limit=limit, offset=offset, request_options=request_options
        )
        return _response.data

    async def list_runs_for_agent(
        self,
        agent_uuid: str,
        *,
        type: typing.Optional[ListRunsForAgentAgentTestsRequestType] = None,
        status: typing.Optional[TaskStatus] = None,
        has_failures: typing.Optional[bool] = None,
        around: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PaginatedResponseAgentTestRunListItem:
        """
        List an agent's test runs with their results

        Parameters
        ----------
        agent_uuid : str
            Agent whose test runs to list

        type : typing.Optional[ListRunsForAgentAgentTestsRequestType]
            Filter by run type. Omit to return both:
            - `llm-unit-test`: single runs of an agent's tests
            - `llm-benchmark`: multi-model comparisons

        status : typing.Optional[TaskStatus]
            Filter by run status. Omit for all statuses

        has_failures : typing.Optional[bool]
            Filter by whether the run has any failing test case or model. `true` returns only runs with failures (or errors), `false` only clean runs. Omit for both

        around : typing.Optional[str]
            ID of a run to jump to, returning the page that contains it instead of the page at `offset`

        limit : typing.Optional[int]
            Maximum number of items to return. Omit for no limit (all items)

        offset : typing.Optional[int]
            Number of items to skip before returning results

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PaginatedResponseAgentTestRunListItem
            Successful Response

        Examples
        --------
        import asyncio

        from calibrate import AsyncCalibrate

        client = AsyncCalibrate(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.agent_tests.list_runs_for_agent(
                agent_uuid="f47ac10b-58cc-4372-a567-0e02b2c3d479",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_runs_for_agent(
            agent_uuid,
            type=type,
            status=status,
            has_failures=has_failures,
            around=around,
            limit=limit,
            offset=offset,
            request_options=request_options,
        )
        return _response.data

    async def bulk_unlink(
        self,
        *,
        agent_uuid: str,
        test_uuids: typing.Sequence[str],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AgentTestsBulkUnlinkResponse:
        """
        Unlink one or more tests from an agent. Tests that are not linked are skipped.

        Parameters
        ----------
        agent_uuid : str
            Agent to unlink tests from

        test_uuids : typing.Sequence[str]
            Tests to unlink from the agent

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AgentTestsBulkUnlinkResponse
            Successful Response

        Examples
        --------
        import asyncio

        from calibrate import AsyncCalibrate

        client = AsyncCalibrate(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.agent_tests.bulk_unlink(
                agent_uuid="f47ac10b-58cc-4372-a567-0e02b2c3d479",
                test_uuids=["b1c2d3e4-f5a6-7890-bcde-f12345678901"],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.bulk_unlink(
            agent_uuid=agent_uuid, test_uuids=test_uuids, request_options=request_options
        )
        return _response.data

    async def run(
        self,
        agent_uuid: str,
        *,
        test_uuids: typing.Optional[typing.Sequence[str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AgentTestRunCreateResponse:
        """
        Run an agent's linked tests as a background job, returning a task ID to poll.

        Parameters
        ----------
        agent_uuid : str
            Agent to test

        test_uuids : typing.Optional[typing.Sequence[str]]
            Tests to run. Omit to run all tests linked to the agent

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AgentTestRunCreateResponse
            Successful Response

        Examples
        --------
        import asyncio

        from calibrate import AsyncCalibrate

        client = AsyncCalibrate(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.agent_tests.run(
                agent_uuid="f47ac10b-58cc-4372-a567-0e02b2c3d479",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.run(agent_uuid, test_uuids=test_uuids, request_options=request_options)
        return _response.data

    async def run_batch(
        self,
        *,
        request: typing.Optional[BatchRunRequest] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> BatchTestRunResponse:
        """
        Run agent tests for every agent, or for a selected set.

        Parameters
        ----------
        request : typing.Optional[BatchRunRequest]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BatchTestRunResponse
            Successful Response

        Examples
        --------
        import asyncio

        from calibrate import AsyncCalibrate, BatchRunRequest

        client = AsyncCalibrate(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.agent_tests.run_batch(
                request=BatchRunRequest(),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.run_batch(request=request, request_options=request_options)
        return _response.data

    async def get_run(
        self,
        task_id: str,
        *,
        only_failed: typing.Optional[bool] = None,
        mode: typing.Optional[GetRunAgentTestsRequestMode] = None,
        compact: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> TestRunStatusResponse:
        """
        Poll a test run for its status and evaluation results.

        Parameters
        ----------
        task_id : str
            Test run to poll for status and results

        only_failed : typing.Optional[bool]
            Return only failing test cases. Omit to return every case

        mode : typing.Optional[GetRunAgentTestsRequestMode]
            How much of each test case to return. `full` returns every field of every case. `summary` returns one light row per case, with its ID, name, verdict and short reason, leaving out the conversation, the agent's output and the evaluator verdicts. Read those one case at a time from `GET /agent-tests/run/{task_id}/results/{test_uuid}`

        compact : typing.Optional[bool]
            Return a compact response that omits heavy detail fields (`results.output`, `results.test_case`, `results.judge_results`, `results.reasoning`, `evaluators.output_config`), keeping only the lightweight decision fields. Omit for full detail

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TestRunStatusResponse
            Successful Response

        Examples
        --------
        import asyncio

        from calibrate import AsyncCalibrate

        client = AsyncCalibrate(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.agent_tests.get_run(
                task_id="a3b2c1d0-e5f4-3210-abcd-ef1234567890",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_run(
            task_id, only_failed=only_failed, mode=mode, compact=compact, request_options=request_options
        )
        return _response.data

    async def get_run_case(
        self,
        task_id: str,
        test_uuid: str,
        *,
        model: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> TestCaseResult:
        """
        Get the full result of one test case in a run

        Parameters
        ----------
        task_id : str
            Test run or benchmark the case was run in

        test_uuid : str
            The test whose result to read, as `test_uuid` on the case

        model : typing.Optional[str]
            Which model's answer to read. Required for a benchmark, which runs every test once per model

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TestCaseResult
            Successful Response

        Examples
        --------
        import asyncio

        from calibrate import AsyncCalibrate

        client = AsyncCalibrate(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.agent_tests.get_run_case(
                task_id="a3b2c1d0-e5f4-3210-abcd-ef1234567890",
                test_uuid="b1c2d3e4-f5a6-7890-bcde-f12345678901",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_run_case(
            task_id, test_uuid, model=model, request_options=request_options
        )
        return _response.data

    async def benchmark(
        self,
        agent_uuid: str,
        *,
        models: typing.Sequence[str],
        test_uuids: typing.Optional[typing.Sequence[str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AgentTestRunCreateResponse:
        """
        Run a multi-model benchmark on an agent's linked tests as a background job.

        Parameters
        ----------
        agent_uuid : str
            Agent to benchmark

        models : typing.Sequence[str]
            Model names to benchmark

        test_uuids : typing.Optional[typing.Sequence[str]]
            A subset of the agent's linked tests to benchmark. Each ID must be linked to the agent. Omit to run all linked tests

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AgentTestRunCreateResponse
            Successful Response

        Examples
        --------
        import asyncio

        from calibrate import AsyncCalibrate

        client = AsyncCalibrate(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.agent_tests.benchmark(
                agent_uuid="f47ac10b-58cc-4372-a567-0e02b2c3d479",
                models=["openai/gpt-4.1", "anthropic/claude-sonnet-4"],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.benchmark(
            agent_uuid, models=models, test_uuids=test_uuids, request_options=request_options
        )
        return _response.data

    async def get_benchmark(
        self,
        task_id: str,
        *,
        only_failed: typing.Optional[bool] = None,
        mode: typing.Optional[GetBenchmarkAgentTestsRequestMode] = None,
        compact: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> BenchmarkStatusResponse:
        """
        Get the results of a benchmark run

        Parameters
        ----------
        task_id : str
            Benchmark run to poll for status and results

        only_failed : typing.Optional[bool]
            Return only failing test cases for each model. Omit to return every case

        mode : typing.Optional[GetBenchmarkAgentTestsRequestMode]
            How much of each test case to return. `full` returns every field of every case. `summary` returns one light row per case, with its ID, name, verdict and short reason, leaving out the conversation, the agent's output and the evaluator verdicts. Read those one case at a time from `GET /agent-tests/run/{task_id}/results/{test_uuid}`

        compact : typing.Optional[bool]
            Return a compact response that omits heavy detail fields (`model_results.test_results`, `evaluators.output_config`), keeping only the lightweight decision fields. Omit for full detail

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BenchmarkStatusResponse
            Successful Response

        Examples
        --------
        import asyncio

        from calibrate import AsyncCalibrate

        client = AsyncCalibrate(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.agent_tests.get_benchmark(
                task_id="a3b2c1d0-e5f4-3210-abcd-ef1234567890",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_benchmark(
            task_id, only_failed=only_failed, mode=mode, compact=compact, request_options=request_options
        )
        return _response.data
