# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import encode_path_param
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..core.serialization import convert_and_respect_annotation_metadata
from ..errors.unprocessable_entity_error import UnprocessableEntityError
from ..types.agent_test_run_create_response import AgentTestRunCreateResponse
from ..types.agent_tests_bulk_unlink_response import AgentTestsBulkUnlinkResponse
from ..types.agent_tests_create_response import AgentTestsCreateResponse
from ..types.batch_run_request import BatchRunRequest
from ..types.batch_test_run_response import BatchTestRunResponse
from ..types.benchmark_status_response import BenchmarkStatusResponse
from ..types.http_validation_error import HttpValidationError
from ..types.paginated_response_agent_test_run_list_item import PaginatedResponseAgentTestRunListItem
from ..types.paginated_response_test_list_response import PaginatedResponseTestListResponse
from ..types.task_status import TaskStatus
from ..types.test_case_result import TestCaseResult
from ..types.test_run_status_response import TestRunStatusResponse
from .types.get_benchmark_agent_tests_request_mode import GetBenchmarkAgentTestsRequestMode
from .types.get_run_agent_tests_request_mode import GetRunAgentTestsRequestMode
from .types.list_for_agent_agent_tests_request_q_mode import ListForAgentAgentTestsRequestQMode
from .types.list_runs_for_agent_agent_tests_request_type import ListRunsForAgentAgentTestsRequestType
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawAgentTestsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def link(
        self,
        *,
        agent_uuid: str,
        test_uuids: typing.Sequence[str],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[AgentTestsCreateResponse]:
        """
        Link one or more tests to an agent. Tests that are already linked are skipped.

        Parameters
        ----------
        agent_uuid : str
            Agent to link tests to

        test_uuids : typing.Sequence[str]
            Tests to link. Any that are already linked are skipped

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[AgentTestsCreateResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            "agent-tests",
            method="POST",
            json={
                "agent_uuid": agent_uuid,
                "test_uuids": test_uuids,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    AgentTestsCreateResponse,
                    parse_obj_as(
                        type_=AgentTestsCreateResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def list_for_agent(
        self,
        agent_uuid: str,
        *,
        type: typing.Optional[typing.Sequence[str]] = None,
        q: typing.Optional[str] = None,
        q_mode: typing.Optional[ListForAgentAgentTestsRequestQMode] = None,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[PaginatedResponseTestListResponse]:
        """
        List the tests linked to an agent.

        Parameters
        ----------
        agent_uuid : str
            Agent whose linked tests to list

        type : typing.Optional[typing.Sequence[str]]
            Keep only tests of these types. Repeat the parameter or pass one comma-separated value. Accepts `response`, `tool_call`, `conversation`, `general`

        q : typing.Optional[str]
            Case-insensitive search on `name`. Blank is a no-op

        q_mode : typing.Optional[ListForAgentAgentTestsRequestQMode]
            How to match `q` against the searched fields

        limit : typing.Optional[int]
            Maximum number of items to return. Omit for no limit (all items)

        offset : typing.Optional[int]
            Number of items to skip before returning results

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[PaginatedResponseTestListResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"agent-tests/agent/{encode_path_param(agent_uuid)}/tests",
            method="GET",
            params={
                "type": type,
                "q": q,
                "q_mode": q_mode,
                "limit": limit,
                "offset": offset,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PaginatedResponseTestListResponse,
                    parse_obj_as(
                        type_=PaginatedResponseTestListResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def list_runs_for_agent(
        self,
        agent_uuid: str,
        *,
        type: typing.Optional[ListRunsForAgentAgentTestsRequestType] = None,
        status: typing.Optional[TaskStatus] = None,
        has_failures: typing.Optional[bool] = None,
        around: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[PaginatedResponseAgentTestRunListItem]:
        """
        List an agent's test runs with their results

        Parameters
        ----------
        agent_uuid : str
            Agent whose test runs to list

        type : typing.Optional[ListRunsForAgentAgentTestsRequestType]
            Filter by run type. Omit to return both:
            - `llm-unit-test`: single runs of an agent's tests
            - `llm-benchmark`: multi-model comparisons

        status : typing.Optional[TaskStatus]
            Filter by run status. Omit for all statuses

        has_failures : typing.Optional[bool]
            Filter by whether the run has any failing test case or model. `true` returns only runs with failures (or errors), `false` only clean runs. Omit for both

        around : typing.Optional[str]
            ID of a run to jump to, returning the page that contains it instead of the page at `offset`

        limit : typing.Optional[int]
            Maximum number of items to return. Omit for no limit (all items)

        offset : typing.Optional[int]
            Number of items to skip before returning results

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[PaginatedResponseAgentTestRunListItem]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"agent-tests/agent/{encode_path_param(agent_uuid)}/runs",
            method="GET",
            params={
                "type": type,
                "status": status,
                "has_failures": has_failures,
                "around": around,
                "limit": limit,
                "offset": offset,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PaginatedResponseAgentTestRunListItem,
                    parse_obj_as(
                        type_=PaginatedResponseAgentTestRunListItem,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def bulk_unlink(
        self,
        *,
        agent_uuid: str,
        test_uuids: typing.Sequence[str],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[AgentTestsBulkUnlinkResponse]:
        """
        Unlink one or more tests from an agent. Tests that are not linked are skipped.

        Parameters
        ----------
        agent_uuid : str
            Agent to unlink tests from

        test_uuids : typing.Sequence[str]
            Tests to unlink from the agent

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[AgentTestsBulkUnlinkResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            "agent-tests/bulk-unlink",
            method="POST",
            json={
                "agent_uuid": agent_uuid,
                "test_uuids": test_uuids,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    AgentTestsBulkUnlinkResponse,
                    parse_obj_as(
                        type_=AgentTestsBulkUnlinkResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def run(
        self,
        agent_uuid: str,
        *,
        test_uuids: typing.Optional[typing.Sequence[str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[AgentTestRunCreateResponse]:
        """
        Run an agent's linked tests as a background job, returning a task ID to poll.

        Parameters
        ----------
        agent_uuid : str
            Agent to test

        test_uuids : typing.Optional[typing.Sequence[str]]
            Tests to run. Omit to run all tests linked to the agent

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[AgentTestRunCreateResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"agent-tests/agent/{encode_path_param(agent_uuid)}/run",
            method="POST",
            json={
                "test_uuids": test_uuids,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    AgentTestRunCreateResponse,
                    parse_obj_as(
                        type_=AgentTestRunCreateResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def run_batch(
        self,
        *,
        request: typing.Optional[BatchRunRequest] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[BatchTestRunResponse]:
        """
        Run agent tests for every agent, or for a selected set.

        Parameters
        ----------
        request : typing.Optional[BatchRunRequest]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[BatchTestRunResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            "agent-tests/run",
            method="POST",
            json=convert_and_respect_annotation_metadata(
                object_=request, annotation=typing.Optional[BatchRunRequest], direction="write"
            ),
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    BatchTestRunResponse,
                    parse_obj_as(
                        type_=BatchTestRunResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get_run(
        self,
        task_id: str,
        *,
        only_failed: typing.Optional[bool] = None,
        mode: typing.Optional[GetRunAgentTestsRequestMode] = None,
        compact: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[TestRunStatusResponse]:
        """
        Poll a test run for its status and evaluation results.

        Parameters
        ----------
        task_id : str
            Test run to poll for status and results

        only_failed : typing.Optional[bool]
            Return only failing test cases. Omit to return every case

        mode : typing.Optional[GetRunAgentTestsRequestMode]
            How much of each test case to return. `full` returns every field of every case. `summary` returns one light row per case, with its ID, name, verdict and short reason, leaving out the conversation, the agent's output and the evaluator verdicts. Read those one case at a time from `GET /agent-tests/run/{task_id}/results/{test_uuid}`

        compact : typing.Optional[bool]
            Return a compact response that omits heavy detail fields (`results.output`, `results.test_case`, `results.judge_results`, `results.reasoning`, `evaluators.output_config`), keeping only the lightweight decision fields. Omit for full detail

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[TestRunStatusResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"agent-tests/run/{encode_path_param(task_id)}",
            method="GET",
            params={
                "only_failed": only_failed,
                "mode": mode,
                "compact": compact,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    TestRunStatusResponse,
                    parse_obj_as(
                        type_=TestRunStatusResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get_run_case(
        self,
        task_id: str,
        test_uuid: str,
        *,
        model: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[TestCaseResult]:
        """
        Get the full result of one test case in a run

        Parameters
        ----------
        task_id : str
            Test run or benchmark the case was run in

        test_uuid : str
            The test whose result to read, as `test_uuid` on the case

        model : typing.Optional[str]
            Which model's answer to read. Required for a benchmark, which runs every test once per model

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[TestCaseResult]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"agent-tests/run/{encode_path_param(task_id)}/results/{encode_path_param(test_uuid)}",
            method="GET",
            params={
                "model": model,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    TestCaseResult,
                    parse_obj_as(
                        type_=TestCaseResult,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def benchmark(
        self,
        agent_uuid: str,
        *,
        models: typing.Sequence[str],
        test_uuids: typing.Optional[typing.Sequence[str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[AgentTestRunCreateResponse]:
        """
        Run a multi-model benchmark on an agent's linked tests as a background job.

        Parameters
        ----------
        agent_uuid : str
            Agent to benchmark

        models : typing.Sequence[str]
            Model names to benchmark

        test_uuids : typing.Optional[typing.Sequence[str]]
            A subset of the agent's linked tests to benchmark. Each ID must be linked to the agent. Omit to run all linked tests

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[AgentTestRunCreateResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"agent-tests/agent/{encode_path_param(agent_uuid)}/benchmark",
            method="POST",
            json={
                "models": models,
                "test_uuids": test_uuids,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    AgentTestRunCreateResponse,
                    parse_obj_as(
                        type_=AgentTestRunCreateResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get_benchmark(
        self,
        task_id: str,
        *,
        only_failed: typing.Optional[bool] = None,
        mode: typing.Optional[GetBenchmarkAgentTestsRequestMode] = None,
        compact: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[BenchmarkStatusResponse]:
        """
        Get the results of a benchmark run

        Parameters
        ----------
        task_id : str
            Benchmark run to poll for status and results

        only_failed : typing.Optional[bool]
            Return only failing test cases for each model. Omit to return every case

        mode : typing.Optional[GetBenchmarkAgentTestsRequestMode]
            How much of each test case to return. `full` returns every field of every case. `summary` returns one light row per case, with its ID, name, verdict and short reason, leaving out the conversation, the agent's output and the evaluator verdicts. Read those one case at a time from `GET /agent-tests/run/{task_id}/results/{test_uuid}`

        compact : typing.Optional[bool]
            Return a compact response that omits heavy detail fields (`model_results.test_results`, `evaluators.output_config`), keeping only the lightweight decision fields. Omit for full detail

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[BenchmarkStatusResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"agent-tests/benchmark/{encode_path_param(task_id)}",
            method="GET",
            params={
                "only_failed": only_failed,
                "mode": mode,
                "compact": compact,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    BenchmarkStatusResponse,
                    parse_obj_as(
                        type_=BenchmarkStatusResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawAgentTestsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def link(
        self,
        *,
        agent_uuid: str,
        test_uuids: typing.Sequence[str],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[AgentTestsCreateResponse]:
        """
        Link one or more tests to an agent. Tests that are already linked are skipped.

        Parameters
        ----------
        agent_uuid : str
            Agent to link tests to

        test_uuids : typing.Sequence[str]
            Tests to link. Any that are already linked are skipped

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[AgentTestsCreateResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            "agent-tests",
            method="POST",
            json={
                "agent_uuid": agent_uuid,
                "test_uuids": test_uuids,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    AgentTestsCreateResponse,
                    parse_obj_as(
                        type_=AgentTestsCreateResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def list_for_agent(
        self,
        agent_uuid: str,
        *,
        type: typing.Optional[typing.Sequence[str]] = None,
        q: typing.Optional[str] = None,
        q_mode: typing.Optional[ListForAgentAgentTestsRequestQMode] = None,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[PaginatedResponseTestListResponse]:
        """
        List the tests linked to an agent.

        Parameters
        ----------
        agent_uuid : str
            Agent whose linked tests to list

        type : typing.Optional[typing.Sequence[str]]
            Keep only tests of these types. Repeat the parameter or pass one comma-separated value. Accepts `response`, `tool_call`, `conversation`, `general`

        q : typing.Optional[str]
            Case-insensitive search on `name`. Blank is a no-op

        q_mode : typing.Optional[ListForAgentAgentTestsRequestQMode]
            How to match `q` against the searched fields

        limit : typing.Optional[int]
            Maximum number of items to return. Omit for no limit (all items)

        offset : typing.Optional[int]
            Number of items to skip before returning results

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[PaginatedResponseTestListResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"agent-tests/agent/{encode_path_param(agent_uuid)}/tests",
            method="GET",
            params={
                "type": type,
                "q": q,
                "q_mode": q_mode,
                "limit": limit,
                "offset": offset,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PaginatedResponseTestListResponse,
                    parse_obj_as(
                        type_=PaginatedResponseTestListResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def list_runs_for_agent(
        self,
        agent_uuid: str,
        *,
        type: typing.Optional[ListRunsForAgentAgentTestsRequestType] = None,
        status: typing.Optional[TaskStatus] = None,
        has_failures: typing.Optional[bool] = None,
        around: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[PaginatedResponseAgentTestRunListItem]:
        """
        List an agent's test runs with their results

        Parameters
        ----------
        agent_uuid : str
            Agent whose test runs to list

        type : typing.Optional[ListRunsForAgentAgentTestsRequestType]
            Filter by run type. Omit to return both:
            - `llm-unit-test`: single runs of an agent's tests
            - `llm-benchmark`: multi-model comparisons

        status : typing.Optional[TaskStatus]
            Filter by run status. Omit for all statuses

        has_failures : typing.Optional[bool]
            Filter by whether the run has any failing test case or model. `true` returns only runs with failures (or errors), `false` only clean runs. Omit for both

        around : typing.Optional[str]
            ID of a run to jump to, returning the page that contains it instead of the page at `offset`

        limit : typing.Optional[int]
            Maximum number of items to return. Omit for no limit (all items)

        offset : typing.Optional[int]
            Number of items to skip before returning results

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[PaginatedResponseAgentTestRunListItem]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"agent-tests/agent/{encode_path_param(agent_uuid)}/runs",
            method="GET",
            params={
                "type": type,
                "status": status,
                "has_failures": has_failures,
                "around": around,
                "limit": limit,
                "offset": offset,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PaginatedResponseAgentTestRunListItem,
                    parse_obj_as(
                        type_=PaginatedResponseAgentTestRunListItem,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def bulk_unlink(
        self,
        *,
        agent_uuid: str,
        test_uuids: typing.Sequence[str],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[AgentTestsBulkUnlinkResponse]:
        """
        Unlink one or more tests from an agent. Tests that are not linked are skipped.

        Parameters
        ----------
        agent_uuid : str
            Agent to unlink tests from

        test_uuids : typing.Sequence[str]
            Tests to unlink from the agent

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[AgentTestsBulkUnlinkResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            "agent-tests/bulk-unlink",
            method="POST",
            json={
                "agent_uuid": agent_uuid,
                "test_uuids": test_uuids,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    AgentTestsBulkUnlinkResponse,
                    parse_obj_as(
                        type_=AgentTestsBulkUnlinkResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def run(
        self,
        agent_uuid: str,
        *,
        test_uuids: typing.Optional[typing.Sequence[str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[AgentTestRunCreateResponse]:
        """
        Run an agent's linked tests as a background job, returning a task ID to poll.

        Parameters
        ----------
        agent_uuid : str
            Agent to test

        test_uuids : typing.Optional[typing.Sequence[str]]
            Tests to run. Omit to run all tests linked to the agent

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[AgentTestRunCreateResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"agent-tests/agent/{encode_path_param(agent_uuid)}/run",
            method="POST",
            json={
                "test_uuids": test_uuids,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    AgentTestRunCreateResponse,
                    parse_obj_as(
                        type_=AgentTestRunCreateResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def run_batch(
        self,
        *,
        request: typing.Optional[BatchRunRequest] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[BatchTestRunResponse]:
        """
        Run agent tests for every agent, or for a selected set.

        Parameters
        ----------
        request : typing.Optional[BatchRunRequest]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[BatchTestRunResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            "agent-tests/run",
            method="POST",
            json=convert_and_respect_annotation_metadata(
                object_=request, annotation=typing.Optional[BatchRunRequest], direction="write"
            ),
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    BatchTestRunResponse,
                    parse_obj_as(
                        type_=BatchTestRunResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get_run(
        self,
        task_id: str,
        *,
        only_failed: typing.Optional[bool] = None,
        mode: typing.Optional[GetRunAgentTestsRequestMode] = None,
        compact: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[TestRunStatusResponse]:
        """
        Poll a test run for its status and evaluation results.

        Parameters
        ----------
        task_id : str
            Test run to poll for status and results

        only_failed : typing.Optional[bool]
            Return only failing test cases. Omit to return every case

        mode : typing.Optional[GetRunAgentTestsRequestMode]
            How much of each test case to return. `full` returns every field of every case. `summary` returns one light row per case, with its ID, name, verdict and short reason, leaving out the conversation, the agent's output and the evaluator verdicts. Read those one case at a time from `GET /agent-tests/run/{task_id}/results/{test_uuid}`

        compact : typing.Optional[bool]
            Return a compact response that omits heavy detail fields (`results.output`, `results.test_case`, `results.judge_results`, `results.reasoning`, `evaluators.output_config`), keeping only the lightweight decision fields. Omit for full detail

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[TestRunStatusResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"agent-tests/run/{encode_path_param(task_id)}",
            method="GET",
            params={
                "only_failed": only_failed,
                "mode": mode,
                "compact": compact,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    TestRunStatusResponse,
                    parse_obj_as(
                        type_=TestRunStatusResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get_run_case(
        self,
        task_id: str,
        test_uuid: str,
        *,
        model: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[TestCaseResult]:
        """
        Get the full result of one test case in a run

        Parameters
        ----------
        task_id : str
            Test run or benchmark the case was run in

        test_uuid : str
            The test whose result to read, as `test_uuid` on the case

        model : typing.Optional[str]
            Which model's answer to read. Required for a benchmark, which runs every test once per model

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[TestCaseResult]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"agent-tests/run/{encode_path_param(task_id)}/results/{encode_path_param(test_uuid)}",
            method="GET",
            params={
                "model": model,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    TestCaseResult,
                    parse_obj_as(
                        type_=TestCaseResult,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def benchmark(
        self,
        agent_uuid: str,
        *,
        models: typing.Sequence[str],
        test_uuids: typing.Optional[typing.Sequence[str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[AgentTestRunCreateResponse]:
        """
        Run a multi-model benchmark on an agent's linked tests as a background job.

        Parameters
        ----------
        agent_uuid : str
            Agent to benchmark

        models : typing.Sequence[str]
            Model names to benchmark

        test_uuids : typing.Optional[typing.Sequence[str]]
            A subset of the agent's linked tests to benchmark. Each ID must be linked to the agent. Omit to run all linked tests

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[AgentTestRunCreateResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"agent-tests/agent/{encode_path_param(agent_uuid)}/benchmark",
            method="POST",
            json={
                "models": models,
                "test_uuids": test_uuids,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    AgentTestRunCreateResponse,
                    parse_obj_as(
                        type_=AgentTestRunCreateResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get_benchmark(
        self,
        task_id: str,
        *,
        only_failed: typing.Optional[bool] = None,
        mode: typing.Optional[GetBenchmarkAgentTestsRequestMode] = None,
        compact: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[BenchmarkStatusResponse]:
        """
        Get the results of a benchmark run

        Parameters
        ----------
        task_id : str
            Benchmark run to poll for status and results

        only_failed : typing.Optional[bool]
            Return only failing test cases for each model. Omit to return every case

        mode : typing.Optional[GetBenchmarkAgentTestsRequestMode]
            How much of each test case to return. `full` returns every field of every case. `summary` returns one light row per case, with its ID, name, verdict and short reason, leaving out the conversation, the agent's output and the evaluator verdicts. Read those one case at a time from `GET /agent-tests/run/{task_id}/results/{test_uuid}`

        compact : typing.Optional[bool]
            Return a compact response that omits heavy detail fields (`model_results.test_results`, `evaluators.output_config`), keeping only the lightweight decision fields. Omit for full detail

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[BenchmarkStatusResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"agent-tests/benchmark/{encode_path_param(task_id)}",
            method="GET",
            params={
                "only_failed": only_failed,
                "mode": mode,
                "compact": compact,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    BenchmarkStatusResponse,
                    parse_obj_as(
                        type_=BenchmarkStatusResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
