# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .agent_test_run_list_item_type import AgentTestRunListItemType
from .model_run_summary import ModelRunSummary
from .task_status import TaskStatus
from .test_run_case_summary import TestRunCaseSummary


class AgentTestRunListItem(UniversalBaseModel):
    uuid_: typing_extensions.Annotated[
        str, FieldMetadata(alias="uuid"), pydantic.Field(alias="uuid", description="Test run job ID")
    ]
    name: str = pydantic.Field()
    """
    Display name, such as `Run 1` for a unit test or `Benchmark 1` for a benchmark
    """

    status: TaskStatus = pydantic.Field()
    """
    Current status of the run
    """

    type: AgentTestRunListItemType = pydantic.Field()
    """
    What kind of run this is:
    - `llm-unit-test`: a single run of the agent's tests
    - `llm-benchmark`: a multi-model comparison
    """

    updated_at: str = pydantic.Field()
    """
    When the run was last updated (ISO 8601 UTC)
    """

    total_tests: typing.Optional[int] = pydantic.Field(default=None)
    """
    Total number of test cases
    """

    passed: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of test cases that passed
    """

    failed: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of test cases that failed
    """

    results: typing.Optional[typing.List[TestRunCaseSummary]] = pydantic.Field(default=None)
    """
    Flat pass/fail summary for each test case (fetch the run detail for full results)
    """

    latency_ms: typing.Optional[typing.Dict[str, typing.Any]] = pydantic.Field(default=None)
    """
    Aggregated latency in milliseconds, as `{p50, p95, p99, count}`
    """

    cost: typing.Optional[typing.Dict[str, typing.Any]] = pydantic.Field(default=None)
    """
    Aggregated cost as `{mean, min, max, count}` (USD)
    """

    total_tokens: typing.Optional[typing.Dict[str, typing.Any]] = pydantic.Field(default=None)
    """
    Aggregated token usage as `{mean, min, max, count}`
    """

    model_results: typing.Optional[typing.List[ModelRunSummary]] = pydantic.Field(default=None)
    """
    Flat summary for each model in a benchmark run (fetch the benchmark detail for full results)
    """

    error: typing.Optional[bool] = pydantic.Field(default=None)
    """
    True if the run failed
    """

    is_public: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether the run is shared publicly
    """

    share_token: typing.Optional[str] = pydantic.Field(default=None)
    """
    Token for building the public share URL
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
