# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .agent_summary_type import AgentSummaryType


class AgentSummary(UniversalBaseModel):
    uuid_: typing_extensions.Annotated[
        str, FieldMetadata(alias="uuid"), pydantic.Field(alias="uuid", description="ID of the agent")
    ]
    name: str = pydantic.Field()
    """
    Name of the agent
    """

    type: AgentSummaryType = pydantic.Field()
    """
    - `agent`: built inside Calibrate
    - `connection`: your existing agent connected to Calibrate
    """

    updated_at: str = pydantic.Field()
    """
    When the agent was last updated (ISO 8601 UTC)
    """

    connection_verified: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether the agent's connection has been verified, for a `type=connection` agent
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
