# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class AnnotatorResponse(UniversalBaseModel):
    uuid_: typing_extensions.Annotated[
        str, FieldMetadata(alias="uuid"), pydantic.Field(alias="uuid", description="Annotator ID")
    ]
    name: str = pydantic.Field()
    """
    Annotator name
    """

    created_at: str = pydantic.Field()
    """
    When the annotator was created (ISO 8601 UTC)
    """

    updated_at: str = pydantic.Field()
    """
    When the annotator was last updated (ISO 8601 UTC)
    """

    jobs_count: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of labelling jobs assigned to this annotator
    """

    current_agreement: typing.Optional[float] = pydantic.Field(default=None)
    """
    Latest pairwise mean agreement with other annotators, from 0 to 1
    """

    pair_count: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of comparable annotation pairs behind the current agreement score
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
