# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class BulkCreateItemsResponse(UniversalBaseModel):
    item_ids: typing.List[str] = pydantic.Field()
    """
    IDs of every item the request resolved to, in request order
    """

    count: int = pydantic.Field()
    """
    How many items the request resolved to
    """

    new_item_ids: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    IDs of the items that were newly created
    """

    existing_item_ids: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    IDs of items that already existed by name and were reused
    """

    annotation_job_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    ID of the labelling job that holds the annotations you provided, present only when you send annotations with the items
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
