# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .chat_message import ChatMessage
from .expected_tool_call import ExpectedToolCall
from .routers_tests_evaluator_ref import RoutersTestsEvaluatorRef


class BulkTestItem(UniversalBaseModel):
    name: str = pydantic.Field()
    """
    Test name, unique within the batch
    """

    conversation_history: typing.List[ChatMessage] = pydantic.Field()
    """
    Ordered messages ending at the user turn the agent should answer (must be non-empty)
    """

    evaluators: typing.Optional[typing.List[RoutersTestsEvaluatorRef]] = pydantic.Field(default=None)
    """
    Evaluators to link. **Required for `response`/`conversation` batches**
    """

    tool_calls: typing.Optional[typing.List[ExpectedToolCall]] = pydantic.Field(default=None)
    """
    Expected tool calls. **Required for `tool_call` batches**
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
