# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .output_config import OutputConfig
from .variable_spec import VariableSpec


class EvaluatorVersionResponse(UniversalBaseModel):
    uuid_: typing_extensions.Annotated[
        str, FieldMetadata(alias="uuid"), pydantic.Field(alias="uuid", description="Version ID")
    ]
    version_number: int = pydantic.Field()
    """
    The version's number. The first version is 1, and it goes up by one for each new version of the evaluator
    """

    judge_model: str = pydantic.Field()
    """
    The model that runs the judge, named the way its provider does, for example `openai/gpt-4.1` or `anthropic/claude-sonnet-4`
    """

    system_prompt: str = pydantic.Field()
    """
    Judge system prompt, with `{{variable}}` placeholders unrendered
    """

    output_config: typing.Optional[OutputConfig] = pydantic.Field(default=None)
    """
    The scale points and their labels. Required for a `rating` evaluator. A `binary` evaluator uses the default Correct/Wrong labels unless you set your own
    """

    variables: typing.Optional[typing.List[VariableSpec]] = pydantic.Field(default=None)
    """
    Declared prompt variables
    """

    created_at: str = pydantic.Field()
    """
    When the version was created (ISO 8601 UTC)
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
