# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .evaluator_run_response_status import EvaluatorRunResponseStatus


class EvaluatorRunResponse(UniversalBaseModel):
    uuid_: typing_extensions.Annotated[
        str, FieldMetadata(alias="uuid"), pydantic.Field(alias="uuid", description="ID of the evaluator-run job")
    ]
    task_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    ID of the task the job ran on
    """

    status: EvaluatorRunResponseStatus = pydantic.Field()
    """
    Current status of the job
    """

    error: typing.Optional[str] = pydantic.Field(default=None)
    """
    Failure reason, present when the job failed
    """

    completed_at: typing.Optional[str] = pydantic.Field(default=None)
    """
    When the job finished (ISO 8601 UTC)
    """

    evaluators: typing.List[typing.Dict[str, typing.Any]] = pydantic.Field()
    """
    The evaluators the job ran, each pinned to the version it used, with that version's rubric
    """

    runs: typing.List[typing.Dict[str, typing.Any]] = pydantic.Field()
    """
    One result per item and evaluator. Each keys back to `evaluators` by its evaluator and version IDs
    """

    human_agreement: typing.Dict[str, typing.Any] = pydantic.Field()
    """
    How each evaluator's judgements line up with the human annotations on the same items
    """

    items: typing.List[typing.Dict[str, typing.Any]] = pydantic.Field()
    """
    The exact item set the job ran on, frozen when the job started
    """

    is_public: bool = pydantic.Field()
    """
    Whether the run is shared publicly
    """

    share_token: typing.Optional[str] = pydantic.Field(default=None)
    """
    Token for building the public share URL
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
