# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .variable_spec import VariableSpec


class EvaluatorLiveVersionSummary(UniversalBaseModel):
    """
    Slim view of the live version for list results, carrying only what the list needs.
    """

    uuid_: typing_extensions.Annotated[
        str, FieldMetadata(alias="uuid"), pydantic.Field(alias="uuid", description="Version ID")
    ]
    version_number: int = pydantic.Field()
    """
    The version's number. The first version is 1, and it goes up by one for each new version of the evaluator
    """

    judge_model: str = pydantic.Field()
    """
    The model that runs the judge, named the way its provider does, for example `openai/gpt-4.1` or `anthropic/claude-sonnet-4`
    """

    variables: typing.Optional[typing.List[VariableSpec]] = pydantic.Field(default=None)
    """
    Declared prompt variables
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
