# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class EvaluatorRunRequestEntry(UniversalBaseModel):
    evaluator_id: str = pydantic.Field()
    """
    Evaluator ID to run. Must be linked to the task
    """

    evaluator_version_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Evaluator version ID to run. Omit to use the evaluator's live version
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
