# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class HumanAgreementBlock(UniversalBaseModel):
    current: typing.Optional[float] = pydantic.Field(default=None)
    """
    Current mean pairwise agreement among annotators
    """

    pair_count: int = pydantic.Field()
    """
    How many annotator pairs the current value averages over
    """

    series: typing.List[typing.Dict[str, typing.Any]] = pydantic.Field()
    """
    Agreement over time, one point per time bucket
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
