# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .labelling_job_created_status import LabellingJobCreatedStatus


class LabellingJobCreated(UniversalBaseModel):
    uuid_: typing_extensions.Annotated[
        str, FieldMetadata(alias="uuid"), pydantic.Field(alias="uuid", description="ID of the labelling job")
    ]
    public_token: str = pydantic.Field()
    """
    Token that opens the annotator's labelling page without signing in
    """

    annotator_id: str = pydantic.Field()
    """
    ID of the annotator the job is assigned to
    """

    annotator_name: str = pydantic.Field()
    """
    Name of the annotator the job is assigned to
    """

    item_ids: typing.List[str] = pydantic.Field()
    """
    IDs of the items assigned to the annotator
    """

    item_count: int = pydantic.Field()
    """
    How many items the annotator has to label
    """

    evaluator_ids: typing.List[str] = pydantic.Field()
    """
    IDs of the evaluators the annotator scores each item on, in the order they are shown
    """

    status: LabellingJobCreatedStatus = pydantic.Field()
    """
    Status of the job right after you create it
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
