# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ModelRunSummary(UniversalBaseModel):
    """
    Flat summary for one model in a benchmark run-LIST item. The full results
    for each case of a model live on the benchmark detail endpoint
    (`GET /agent-tests/benchmark/{task_id}`), not here.
    """

    model: str = pydantic.Field()
    """
    Model name these results are for
    """

    success: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether this model's run succeeded
    """

    message: typing.Optional[str] = pydantic.Field(default=None)
    """
    Status or result message for this model
    """

    total_tests: typing.Optional[int] = pydantic.Field(default=None)
    """
    Total test cases for this model
    """

    passed: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of test cases that passed for this model
    """

    failed: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of test cases that failed for this model
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
