# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class OutputScaleEntry(UniversalBaseModel):
    """
    One entry in an evaluator's output_config.scale. `value` is bool|number|string
    depending on output_type.
    """

    value: typing.Any
    name: str = pydantic.Field()
    """
    Short label for this scale point
    """

    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    Rubric text for this level, added to the judge prompt. Omit to leave this level undescribed
    """

    color: typing.Optional[str] = pydantic.Field(default=None)
    """
    Color to show for this level. Omit for the default
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
