# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class PaginationMeta(UniversalBaseModel):
    total: int = pydantic.Field()
    """
    Total number of items that match, across all pages
    """

    limit: int = pydantic.Field()
    """
    Maximum number of items returned in this page
    """

    offset: int = pydantic.Field()
    """
    Number of items skipped before this page
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
