# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .routers_agents_agent_response_type import RoutersAgentsAgentResponseType


class RoutersAgentsAgentResponse(UniversalBaseModel):
    uuid_: typing_extensions.Annotated[
        str, FieldMetadata(alias="uuid"), pydantic.Field(alias="uuid", description="ID of the agent")
    ]
    name: str = pydantic.Field()
    """
    Human-readable name of the agent
    """

    type: RoutersAgentsAgentResponseType = pydantic.Field()
    """
    `agent` (managed defaults) or `connection` (your own endpoint)
    """

    config: typing.Optional[typing.Dict[str, typing.Any]] = pydantic.Field(default=None)
    """
    Agent configuration
    """

    created_at: str = pydantic.Field()
    """
    When the agent was created (ISO 8601 UTC)
    """

    updated_at: str = pydantic.Field()
    """
    When the agent was last updated (ISO 8601 UTC)
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
