# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .routers_agent_tests_test_response_type import RoutersAgentTestsTestResponseType


class RoutersAgentTestsTestResponse(UniversalBaseModel):
    uuid_: typing_extensions.Annotated[
        str, FieldMetadata(alias="uuid"), pydantic.Field(alias="uuid", description="Test ID")
    ]
    name: str = pydantic.Field()
    """
    Name of the test
    """

    type: RoutersAgentTestsTestResponseType = pydantic.Field()
    """
    What the test checks:
    - `response`: judges the reply the agent generates
    - `tool_call`: checks the tool calls the agent makes
    - `conversation`: judges the full conversation after the agent replies
    """

    config: typing.Optional[typing.Dict[str, typing.Any]] = pydantic.Field(default=None)
    """
    Test configuration
    """

    created_at: str = pydantic.Field()
    """
    When the test was created (ISO 8601 UTC)
    """

    updated_at: str = pydantic.Field()
    """
    When the test was last updated (ISO 8601 UTC)
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
