# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .evaluator_version_response import EvaluatorVersionResponse
from .routers_evaluators_evaluator_response_data_type import RoutersEvaluatorsEvaluatorResponseDataType
from .routers_evaluators_evaluator_response_evaluator_type import RoutersEvaluatorsEvaluatorResponseEvaluatorType
from .routers_evaluators_evaluator_response_output_type import RoutersEvaluatorsEvaluatorResponseOutputType


class RoutersEvaluatorsEvaluatorResponse(UniversalBaseModel):
    uuid_: typing_extensions.Annotated[
        str, FieldMetadata(alias="uuid"), pydantic.Field(alias="uuid", description="Evaluator ID")
    ]
    name: str = pydantic.Field()
    """
    Evaluator name
    """

    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    What the evaluator checks
    """

    evaluator_type: RoutersEvaluatorsEvaluatorResponseEvaluatorType = pydantic.Field()
    """
    What the evaluator judges:
    
    - `tts`: TTS audio
    - `stt`: one transcript
    - `llm`: a reply with its conversation history
    - `llm-general`: a standalone input and output pair
    - `conversation`: a full conversation
    """

    data_type: RoutersEvaluatorsEvaluatorResponseDataType = pydantic.Field()
    """
    The modality the judge reads:
    
    - `text`
    - `audio`
    """

    output_type: RoutersEvaluatorsEvaluatorResponseOutputType = pydantic.Field()
    """
    How the evaluator scores:
    
    - `binary`: pass or fail
    - `rating`: a numeric score, using the scale in `output_config`
    """

    is_default: bool = pydantic.Field()
    """
    True for a built-in default evaluator, which you can't edit. False for an evaluator you created, which you can edit and add versions to
    """

    slug: typing.Optional[str] = pydantic.Field(default=None)
    """
    Stable slug for a built-in default evaluator
    """

    live_version_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    ID of the version that is currently live
    """

    created_at: str = pydantic.Field()
    """
    When the evaluator was created (ISO 8601 UTC)
    """

    updated_at: str = pydantic.Field()
    """
    When the evaluator was last updated (ISO 8601 UTC)
    """

    live_version: typing.Optional[EvaluatorVersionResponse] = pydantic.Field(default=None)
    """
    The version that is currently live
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
