# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .routers_tests_test_response_type import RoutersTestsTestResponseType


class RoutersTestsTestResponse(UniversalBaseModel):
    uuid_: typing_extensions.Annotated[
        str, FieldMetadata(alias="uuid"), pydantic.Field(alias="uuid", description="Unique ID for the test")
    ]
    name: str = pydantic.Field()
    """
    Name of the test
    """

    type: RoutersTestsTestResponseType = pydantic.Field()
    """
    What the test judges:
    
    - `response`: judges the generated reply
    - `tool_call`: diffs the generated tool calls
    - `conversation`: judges the full conversation
    """

    config: typing.Optional[typing.Dict[str, typing.Any]] = pydantic.Field(default=None)
    """
    Config for the test (`history`, `evaluation`, optional `settings`)
    """

    created_at: str = pydantic.Field()
    """
    Timestamp when the test was created (ISO 8601 UTC)
    """

    updated_at: str = pydantic.Field()
    """
    Timestamp when the test was last updated (ISO 8601 UTC)
    """

    evaluators: typing.Optional[typing.List[typing.Dict[str, typing.Any]]] = pydantic.Field(default=None)
    """
    Linked evaluators, resolved to their current live version at read time
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
