# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class RunListEvaluator(UniversalBaseModel):
    """
    One evaluator on a run-LIST row: just enough to name it and open it.
    The rubric, prompt and version live on the run-DETAIL endpoint.
    """

    uuid_: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="uuid"),
        pydantic.Field(
            alias="uuid",
            description="ID of the evaluator. Absent for the `Tool call` entry, which is not an evaluator in the library",
        ),
    ] = None
    name: str = pydantic.Field()
    """
    Name of the evaluator
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
