# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .pagination_meta import PaginationMeta
from .task_summary_response_task_type import TaskSummaryResponseTaskType


class TaskSummaryResponse(UniversalBaseModel):
    task_id: str = pydantic.Field()
    """
    ID of the task
    """

    task_type: TaskSummaryResponseTaskType = pydantic.Field()
    """
    Type of the task
    """

    evaluators: typing.List[typing.Dict[str, typing.Any]] = pydantic.Field()
    """
    The task's evaluators, stable across pages, each with its live rubric
    """

    annotators: typing.List[typing.Dict[str, typing.Any]] = pydantic.Field()
    """
    The annotators who labelled or commented on items in the task, stable across pages
    """

    rows: typing.List[typing.Dict[str, typing.Any]] = pydantic.Field()
    """
    One row per item, evaluator, and version on this page, with the evaluator's value and each annotator's label
    """

    item_comments: typing.Optional[typing.Dict[str, typing.Any]] = pydantic.Field(default=None)
    """
    Annotator comments, keyed by item ID
    """

    pagination: PaginationMeta = pydantic.Field()
    """
    Where this page sits in the full item list
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
