# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .human_agreement_block import HumanAgreementBlock


class TaskAgreementResponse(UniversalBaseModel):
    task_id: str = pydantic.Field()
    """
    ID of the task
    """

    bucket: str = pydantic.Field()
    """
    Time bucket used for the trend series
    """

    days: int = pydantic.Field()
    """
    Length of the trailing window in days
    """

    human_human: HumanAgreementBlock = pydantic.Field()
    """
    Agreement between annotators who labelled the same items
    """

    evaluators: typing.List[typing.Dict[str, typing.Any]] = pydantic.Field()
    """
    Agreement between each evaluator and the annotators, one entry per linked evaluator
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
