# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class TestRunCaseSummary(UniversalBaseModel):
    """
    Flat summary for one test case in the run-LIST endpoints. Carries only
    enough to render a run's pass/fail breakdown and a case name. The full detail
    for each case (agent output, judge verdicts, reasoning, latency, cost, the
    test-case definition) lives on the run-DETAIL endpoint
    (`GET /agent-tests/run/{task_id}`).
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Name of the test case
    """

    passed: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether the case passed (null if it errored or is still running)
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
