# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .tool_call_output import ToolCallOutput


class TestOutput(UniversalBaseModel):
    response: typing.Optional[str] = pydantic.Field(default=None)
    """
    The reply the agent generated
    """

    tool_calls: typing.Optional[typing.List[ToolCallOutput]] = pydantic.Field(default=None)
    """
    Tool calls the agent generated
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
