# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class TraceToolCall(UniversalBaseModel):
    tool: str = pydantic.Field()
    """
    Name of the tool the agent called
    """

    arguments: typing.Optional[typing.Dict[str, typing.Any]] = pydantic.Field(default=None)
    """
    Argument values the agent passed to the tool. Omit when the call had none
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
